### ISSUE TITLE
Exception when starting game

### ISSUE THREAD

**Issue by yghost** [googleads/googleads-mobile-plugins#1]
Hello,
Even with the latest version, i'm getting the following error : 
Exception: JNI: Init'd AndroidJavaClass with null ptr!

Full stack trace : 
Exception: JNI: Init'd AndroidJavaClass with null ptr!
UnityEngine.AndroidJavaClass..ctor (IntPtr jclass)
UnityEngine.AndroidJavaObject.get_JavaLangClass ()
UnityEngine.AndroidJavaObject.FindClass (System.String name)
UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className)
UnityEngine.AndroidJavaClass..ctor (System.String className)
GoogleMobileAdsPlugin.CreateBannerView (System.String publisherId, .AdSize adSize, Boolean positionAtTop) (at Assets/Plugins/GoogleMobileAdsPlugin/GoogleMobileAdsPlugin.cs:48)
GoogleMobileAdsDemoScript.Start () (at Assets/Plugins/GoogleMobileAdsPlugin/GoogleMobileAdsDemoScript.cs:10)

I've imported the unitypackage in my project and copied the google-play-services_lib folder in the /Plugins/android folder.

I've tried several versions of the plugin but can't get it to work.
Tried on a real device, same result.

**Comment by rampara** [comment]
This issue is being closed due to its age. If you still have issues with the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

- Ram
