### ISSUE TITLE
bannerView.Hide() & bannerView.Show() Not Working

### ISSUE THREAD

**Issue by iftah** [googleads/googleads-mobile-plugins#10]
Hi,

The methods bannerView.Hide() & bannerView.Show() are not working, the banner ad is always shown even when I call bannerView.Hide().

This is the class I'm using:

using UnityEngine;
using System.Collections;
using GoogleMobileAds.Api;

public class AdMobController : MonoBehaviour {

	BannerView bannerView;

	void Start () {
		// Create a 320x50 banner at the top of the screen.
		bannerView = new BannerView("ca-app-pub-xxxxx/xxxxxx", AdSize.Banner, AdPosition.Top);
		// Create an empty ad request.
		AdRequest request = new AdRequest.Builder()
                              .AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator
                              .Build();
		// Load the banner with the request.
		bannerView.LoadAd(request);
	}

	void Update() {
		if (Application.loadedLevelName == "Main") {
			bannerView.Hide();
		}
		else {
			bannerView.Show();
		}
	}
}

Any ideas??

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

- Ram
