### ISSUE TITLE
Interstitial doesnt show up 

### ISSUE THREAD

**Issue by samadmalik** [googleads/googleads-mobile-plugins#101]
Hi. Banners are working perfectly in both Android and iOS but interstitial doesn't show up at all. 

		#if UNITY_ANDROID
		interstitial = new InterstitialAd("ca-app-pub-2446119148354984/3322xxxxxx");
		AdRequest request = new AdRequest.Builder().Build();
		interstitial.LoadAd(request);
		
		if (interstitial.IsLoaded()) {
			interstitial.Show();
		}

		#endif

What could be the issue?

**Comment by jjjuande** [comment]
You need to give some time for the ad to be downloaded after the call to LoadAd. Otherwise, interstitial.IsLoaded is going to return false. (Because the ad had no time to be downloaded)

**Comment by samadmalik** [comment]
Thanks for the quick reply. The documentation doesn't outline this. Or does it? How can I make it work anyway?

**Comment by jjjuande** [comment]
I made this asset https://github.com/jjjuande/EasyGoogleMobileAds/blob/master/README-EN.md that works on top of this plugin to make its use even easier. Check it out.

**Comment by samadmalik** [comment]
It worked! Thanks a lot man! :)

**Comment by jjjuande** [comment]
Great! :)

**Comment by samadmalik** [comment]
Just a quick question. I am initializing this in Awake method:
EasyGoogleMobileAds.GetInterstitialManager().PrepareInterstitial("ca-app-pub-2446119148354984/3322xxxxxx");

and for testing purpose, I am loading interstitial on button click. It takes a few seconds before the interstitial is downloaded. How can I wait for the interstitial to be finished downloading and then show it automatically. For example:

if (interstitial.IsLoaded()) {
EasyGoogleMobileAds.GetInterstitialManager().ShowInterstitial();
}

**Comment by jjjuande** [comment]
You could use the interstitial's events. But it's not a good idea since the interstitial must be showed at certain points of transition in your game. Not in the middle of any task (When the ad is downloaded and ready to be shown).

**Comment by samadmalik** [comment]
Alright I got it. Thanks again man!
