### ISSUE TITLE
Umbrella header 'GoogleMobileAds' not found

### ISSUE THREAD

**Issue by abeldantas** [googleads/googleads-mobile-plugins#103]
Hi, there's a thread, #77 where some people have discussed a similar problem.
The solution in there isn't working for me.

Can someone help me debug this?

![screen shot 2015-05-26 at 11 07 44](https://cloud.githubusercontent.com/assets/1776096/7810142/7b104c10-0397-11e5-908b-7559164f506e.png)

Umbrella header 'GoogleMobileAds.h' not found.

In #77 the problem was that the uncompression messed up the symlinks, however, that doesnt seem to be what is happening in my case:

![framework](https://cloud.githubusercontent.com/assets/1776096/7810155/8c6c3ae6-0397-11e5-8510-56d57204b4ea.png)

Some other usual suspects:

![screen shot 2015-05-26 at 11 10 39](https://cloud.githubusercontent.com/assets/1776096/7810211/01975026-0398-11e5-872a-e5ee97e2b32c.png)
![screen shot 2015-05-26 at 11 08 57](https://cloud.githubusercontent.com/assets/1776096/7810212/019ac8aa-0398-11e5-9711-1414e112f1fc.png)

![screen shot 2015-05-26 at 11 13 12](https://cloud.githubusercontent.com/assets/1776096/7810252/414479e2-0398-11e5-8c19-5146f432f507.png)

I think I'm using the up to date versions of everything.

I'm using 7.2.2 googlemobileadssdkios.zip found here : https://developers.google.com/mobile-ads-sdk/download , that one is for the GoogleMobileAds.framework that is linked in the project.

My project is in unity, so I'm using googleads-mobile-plugins 2.2.1, found here https://github.com/googleads/googleads-mobile-plugins , that one is for the files that go into the assets and plugins folder of the Unity project

I've tried a lot of stuff and nothing is working, what am I missing?

**Comment by rampara** [comment]
If you were to upload your version of GoogleMobileAds.framework I can try to troubleshoot further.

- Ram

**Comment by abeldantas** [comment]
@rampara Thanks!

(GoogleMobileAds.framework.zip)[abeldantas.com/upload/GoogleMobileAds.framework.zip]

**Comment by rampara** [comment]
The link you provided seems to be broken.

- Ram

**Comment by abeldantas** [comment]
indeed, sorry about that, [here](http://abeldantas.com/upload/GoogleMobileAds.framework.zip)

**Comment by rampara** [comment]
Using the framework you linked I'm able to build and run a project without issue. Which version of Xcode are you using?

- Ram

**Comment by abeldantas** [comment]
Version 6.1.1 (6A2008a)

Could it be the order of the framework, or perhaps the GADU files need some tweaking.

**Comment by SevenAntares** [comment]
Hi, I have exactly the same problem in xcode 5.1.1 (5B1008)

**Comment by abeldantas** [comment]
I've tried everything I could think of and nothing works, which makes me wonder if googleads-mobile-plugins 2.2.1 Unity plugin is even working with this version of GoogleMobileAds.framework.

@SevenAntares On other projects I have an older versions of the plugin and framework which are working just fine, I'm thinking of getting it from an older project and integrating it, I wouldn't mind sending you the files as well.

Still, I'd appreciate if someone that has had success with the unity plugin and this new version of the framework could confirm me that they do work.

Thanks

**Comment by SevenAntares** [comment]
@abeldantas, i would be very grateful if you share with me. I've tried everything. My game takes delayed a month because of this. Thanks

**Comment by rampara** [comment]
Are you seeing this problem on the sample application linked at https://github.com/googleads/googleads-mobile-plugins/tree/master/unity/samples/HelloWorld as well?

- Ram

**Comment by abeldantas** [comment]
No, I'm not, thus, the problem was somewhere in the unity project plugin.
Upon removing all traces of the plugin and using the most up to date version, I stopped having this problem.

I still have no idea on what caused the problem. Using the up to date files in both repos should work for everyone else. @SevenAntares, can you try this and let us know if it works for you too, so I can mark this as closed?

**Comment by SevenAntares** [comment]
I upgraded to Yosemite and Xcode 6.3 and now works perfectly

**Comment by walkerxian** [comment]
@abeldantas  ,Do you have solve the problem?My version of XCode is 7.1.1 and  version of GoogleMobileAdsSdkiOS-7.6.0,I have the same error hint:Umbrella header 'GoogleMobileAds' not found

**Comment by walkerxian** [comment]
@abeldantas ,Hi,I have been sovled the problem,Because I download the GoogleMobileAds.zip on windows ,May be lost some information while downloading the zip file, so  i download the file again on mac .Now ,Anything is ok ,and thank you again!

**Comment by pankaj8958** [comment]
I resolve this issue by 
>re-downloading the google mobile ads sdk in my case Google-Mobile-Ads-SDK-7.24.1 
>removing old sdk from linked framework... 
>removing from framework directory and deleting all
>then placing new sdk in the place
>and editting search path for framework and header in build settings > search path pointing to new sdk

I know it doesn't make :) 
hope that works for someone :)
