### ISSUE TITLE
Ads won't work without test device

### ISSUE THREAD

**Issue by adquestionthrowaway** [googleads/googleads-mobile-plugins#104]
I've been trying away for hours now to get banner ads to work properly (Unity 5.0.1, GMA 2.2.1)

I couldn't get it working with the "least amount of code" writeup on here for banner ads, it'd either tell me I was missing a comma, or if I placed the LoadAd call in a start function (importing UnityEngine) then it wouldn't throw an error, but my game would crash on start. However the demo script (GoogleMobileAdsDemoScript.cs) worked fine, so after some stripping away, I found it was without the testdevice portion of code that it wouldn't work. Mind you, I'm not using any unique device IDs for the test device or anything, just the defaults provided.

**Comment by rampara** [comment]
I am having trouble replicating this problem. I removed the lines below from the createAdRequest() method in GoogleMobileAdsDemoScript.cs and was able to display live ads without issue.

    .AddTestDevice(AdRequest.TestDeviceSimulator)
    .AddTestDevice("0123456789ABCDEF0123456789ABCDEF")

- Ram

**Comment by adquestionthrowaway** [comment]
I just really can't get them to work for the life of me. At first they would work every few times of loading the game, but now it's just never. Nothing I do is working. :(

**Comment by adquestionthrowaway** [comment]
So just to confirm how to actually set this up, I download the two source folders, place the GoogleMobileAds folder and Plugins folder into the Asset folder of Unity, get the google-play-services_lib folder from the ANDROID_SDK_LOCATION/extras/google/google_play_services/libproject folder, place it in Plugins/Android from above, and then I should be able to import the demo script and scene file from the Hello World project, confirm Android is the selected platform load the scene, and it works. Right?

There's a few confusing things here. Firstly, the demo scene is broken; the script reference is missing. I guess it used to have a different name or something, or I'm doing something wrong. But adding the demo script to the camera and removing the missing one, following the instructions of doing a Build & Run, it loads up on my phone, 7 buttons to request, show, hide etc. Pressing them doesn't do anything. Now, there's a folder in the source folder called "plugin-library" not mentioned in the instructions. I decided maybe it was overlooked, and I added it matchingly along side the asset folder which had to of course be done from windows explorer since you can't add outside of the asset folder within Unity. Close the project, reload, just in case Unity only refreshes the Asset folder. No go. So again going beyond the instructions, I go ahead and enter my app ID in the demo script under the #elif UNITY_ANDROID spot, thinking maybe it would help, and it doesn't. 

I assume I did something wrong somewhere, but I followed the instructions pretty exactly (for Android) and it's not doing it for me. I went ahead and tried the basic banner flow example but no-go again. No amount of tweaking either script did any good for me, but again I'm just assuming it's something higher up. 

The "Integrate the Plugin into your Game" isn't valid anymore as there is no unityasset package.

**Comment by rampara** [comment]
You should't have to download source folders. You can just import the latest unity plugin package from https://github.com/googleads/googleads-mobile-plugins/releases. Are you following the instructions from our read me at https://github.com/googleads/googleads-mobile-plugins/blob/master/unity/README.md ?

If the demo script is not already attached to a game object you will have to do so.

**Comment by adquestionthrowaway** [comment]
I followed the instructions in that link. I didn't see that first thing anywhere. I assumed the source would do it. It does work now; so success!  Thank you. :) 

Edit: Upon further review, I see the thing about releases on the main page there; I didn't see it till just now. When googling I was linked directly to googleads-mobile-plugins/unity/ and assumed that the unitypackage was an oudated reference since I didn't see it anywhere, and simply downloaded the source.

**Comment by rampara** [comment]
Glad you were able to get your project working.
