### ISSUE TITLE
Problems with Xcode 6.3.

### ISSUE THREAD

**Issue by LazarGabriel** [googleads/googleads-mobile-plugins#105]
Hi, i'm trying to implement Admob ads in my Unity3d game.

I followed all the installations rules found here: https://github.com/googleads/googleads-mobile-plugins/blob/master/unity/README.md

Everything worked perfect until the 3rd step: Set Enable Modules (C and Objective-C) to Yes in Build Settings.

I wasn't able to find "Enable Modules" in Xcode. I searched on google and i found out that "with the new Xcode update you don't have to enable modules because they are enabled automatically". Another thing that i wasn't able to was to: " From the Xcode project navigator, right-click on the project, and choose Add Files To "" " because i wasn't able to find "Add Files To"" ". So i tried to build the game, and here comes the problem. I get like 50 errors like this:
http://s11.postimg.org/s24kgyn8z/Screen_Shot_2015_05_31_at_12_36_04_AM.png

I tried to find this on google and all i found is for older Xcode versions. (and something with # instead of @ at imports but it doesn't work, or i don't know where should i use @ and where should i use #) I saw that you can set modules enabled in AppleLLMV 6.0 but i have 6.1.

I'm using Version 6.3 (6D570) and iOS 7.3.1 .

Thank you for reading this and trying to help me !

**Comment by KyDenZ** [comment]
Yes I also renontre full error.

Would it be possibe to have the new files to Xcode 6.3 and SDK 7.3.1 Google

thank you

**Comment by rampara** [comment]
Within Xcode 6.3.1 I am able to find both the "Enable modules (C and Objective-C)" and "Add Files to *project name*" options. I have attached a screenshot below.

![screen shot 2015-06-02 at 1 34 49 pm](https://cloud.githubusercontent.com/assets/11047881/7946566/3586ecc2-092c-11e5-96b5-147c909d9e66.png)


- Ram

**Comment by LazarGabriel** [comment]
I've tried again to do it.
I installed XCode Version 6.3.1 (6D1002). I was able to find Add Files to
"Unity-iPhone" and i did it.
After that i linked googleMobileAds.framework. (i attached a printscreen)
Then, the last step: i searched in the search bar, in build settings
 "enable modules", as you did and nothing found. (i attached a printscreen).

Before i opened XCode project i added googlemobileplugin.package in my
unity project and build it. (the only thing that i didn't do was to put a
real id for ad_unit_id, but i don't think that's a problem).

Do you think that i need something more than XCode to see Apple LLVM 6.1 -
Language - Modules ?

Errors are the same. (i attached printscreen).
I downloaded XCode Version 6.3.1 (6D1002) from
https://developer.apple.com/downloads/ (attached printscreen). I have to
mention that it is the only thing that i downloaded.

PS: I'm using OS X YOSEMITE Version: 10.10.3 (14D136) and i'm not a mac
user. (I bought it just for developing for ios and i don't have experience
in using the System or XCode).

2015-06-02 23:36 GMT+03:00 rampara <notifications@github.com>:

**Comment by rampara** [comment]
The am unable to view any of the screenshots you mention attaching.

- Ram

**Comment by LazarGabriel** [comment]
Can't you see it in your email ?

2015-06-03 0:02 GMT+03:00 rampara <notifications@github.com>:

**Comment by rampara** [comment]
Not through email or github.
