### ISSUE TITLE
Error compiling for android using Unity 5.1 

### ISSUE THREAD

**Issue by rbreve** [googleads/googleads-mobile-plugins#108]
I just upgraded to 5.1 but I'm getting 

IndexOutOfRangeException: Array index is out of range. error when compiling, it only happens with android.

**Comment by rampara** [comment]
Can you provide more details on the error you are seeing. I am able to build and run our sample application on Unity 5.1.2, without any errors.

- Ram

**Comment by rbreve** [comment]
I solved it deleting a AndroidManifest.xml the problem is that unity
couldn't merge AndroidManifests with other libraries, so I modified it, and
got that error, then I proceded to delete the contents and the problem was
fixed. Thanks

**Comment by rampara** [comment]
Glad you were able to get this sorted out.

- Ram
