### ISSUE TITLE
Unity Admob Mediation instructions?

### ISSUE THREAD

**Issue by timmy2702** [googleads/googleads-mobile-plugins#112]
Hi,

I'm trying to integrate admob mediation for Unity. However, I can't find any instructions or tutorials about this one. I saw the mediation folder in this repository. Can you guys help me or guide me on how to implement this?

Thanks :)

**Comment by ericleich** [comment]
Hi there,

The mediation_adapter folder in this repo is actually for a different project.

There are some instructions [here](https://developers.google.com/admob/games#admob_mediation_support) on how to add mediation to a Unity project (basically putting libraries in the right place). If you have any further questions about this, please reach out to us on the [developer forum](groups.google.com/group/google-admob-ads-sdk). We try to keep the scope of open issues to only bugs with the plugin.
