### ISSUE TITLE
Soomla and AdMob conflict

### ISSUE THREAD

**Issue by LukasBaran7** [googleads/googleads-mobile-plugins#114]
Hey, I've done what was suggested by @ericleich but when I try app on mobile device, the app is crashing. Is there any way to make Soomla and AdMob work together?

**Comment by ericleich** [comment]
I'm assuming you mean you tried https://github.com/googleads/googleads-mobile-plugins/issues/111#issuecomment-118910403. What is the crash you're seeing?

**Comment by LukasBaran7** [comment]
I've managed to solve the problem by manually removing conflicting files from jar and rebuilding the project. Thanks for help anyway :)
