### ISSUE TITLE
What is InAppBillingService doing in the Banner SDK?

### ISSUE THREAD

**Issue by khambadkone** [googleads/googleads-mobile-plugins#117]
We build Unity games with several plugins.

I'm wondering why the InAppBillingService is bundled as part of GoogleAds SDKs?

**Comment by ericleich** [comment]
The Google Mobile Ads SDK supports [in app purchase ads](https://developers.google.com/admob/android/iap). v2.3.0 of the Unity plugin added support for this feature. This feature depends on the InAppBillingService. To make it easier to use the plugin, we include the InAppBillingService as part of the plugin.

If you 1) Aren't using in-app purchase ads, or 2) have other Unity plugins that already include this service, simply don't include the in-app-billing-service-aidl.jar file when importing the 2.3.1 release of the .unitypackage.
