### ISSUE TITLE
Test Ads shown on other devices as well

### ISSUE THREAD

**Issue by AgentKnopf** [googleads/googleads-mobile-plugins#118]
I am using the google admob unity plugin while targeting Android devices. To set up ads I followed the instructions as outlined here: https://github.com/googleads/googleads-mobile-plugins/tree/master/unity.

Since I am currently testing with some friends I used this snippet to request test ads:

```
AdRequest request = new AdRequest.Builder()
    .AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
    .AddTestDevice("0123456789ABCDEF0123456789ABCDEF")  // Test Device 1.
    .Build();
```

I replaced the device id with the device id of my phone. 

What works: 
I get test ads shown on my phone correctly and it does not change the impression count in admob (as far as i can see).

What doesn't work (?)
My friends see ads as well (real ads - not just test ads)! And they absolutely should not. They should either see no ads at all (since their device id is not used) or test ads at max (though that would make me wonder about the purpose of adding your own device id if ads get shown on other devices anyway).

I also noticed that my friends seeing ads counts towards my impression count in admob ! The problem is: Admob could ban me for this - because you're not supposed to use/see real ads when testing. However - my friends should not be seeing real ads int he first place since I am specifically requesting test ads.

Did I miss something? Am I doing something wrong?

**Comment by rampara** [comment]
When you provided your friends with your application, did you modify the test id used in the addTestDevice() method to match the device they will be using? If the test device id passed to the addTestDevice()method does not match the device currently being used, live ads will be shown. To ensure you always get test ads you can use a test ad unit.

- Ram

**Comment by AgentKnopf** [comment]
Thanks for getting back to me on this. The answer is no - all my friends use the same apk file and that contains my device id (hardcoded). Thank you for pointing out, that that actually is a problem. As for your last suggestion: How/Where do I get a test ad unit? Is it a specific device id that identifies every device as a test device? Thank you in advance!

**Comment by rampara** [comment]
For Android, use the following ad units to ensure you always receive test ads:

Banner: ca-app-pub-3940256099942544/6300978111
Interstitial: ca-app-pub-3940256099942544/1033173712

- Ram

**Comment by AgentKnopf** [comment]
Thank you very much for those ad units! If it isn't currently documented I think documenting it might be a good idea. And in case I missed it, I sincerely apologize :)
