### ISSUE TITLE
Support for TopLeft, TopRight,... and/or custom position

### ISSUE THREAD

**Issue by n-studio** [googleads/googleads-mobile-plugins#12]
I might make a PR for this one, if I have time, not sure I will :/

**Comment by rampara** [comment]
The current version of the plugin is now v2.2 and includes support for additional banner positions. If you are running Unity 5.0 you will have to delete the top-level Android manifest from the Assets/Plugins/Android folder. If you are running on older versions of Unity, replace the top-level manifest file with the one linked below.

https://drive.google.com/a/google.com/file/d/0B3mVbrRS6xpKWDQ5SGVlVUx3clU/view?usp=sharing

Ram
