### ISSUE TITLE
Question about using plugin on iOS

### ISSUE THREAD

**Issue by obywan** [googleads/googleads-mobile-plugins#15]
I have app running on iOS which is not released yet, and I want add this plugin to my app. Build passed without errors, but I can see only test ad (when test device is specified) unlike it was on Android. Is it normal? Or I must do some additional steps to show normal ad on iOS? Thanks.

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

- Ram
