### ISSUE TITLE
Events not called from the Main Thread

### ISSUE THREAD

**Issue by chomi3** [googleads/googleads-mobile-plugins#20]
Hi

Admob event delegates are not called from the Main Thread, and I can't pause / unpause my game when using them. 

Is there any particular way needed to be used, in order to make delegate methods (AdClosed etc) be run on Main Thread?

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

Ram
