### ISSUE TITLE
Banner Ads cover whole screen in white on Android (when using Ad Mediation)

### ISSUE THREAD

**Issue by JDRitchey** [googleads/googleads-mobile-plugins#25]
When using Ad Mediation, setting a Banner Ad visible results in the entire screen being white, with the ad banner at the top (and sometimes top/left).

Everything works fine with regular Ad Mob ads.
The problem does not occur on iOS.

I'm using the Unity Plugin
I'm using MMedia as ad mediation 

-------Possible fix --------
I sent MMedia a help request, and they informed me that this problem occurs when your ads do not have explicit size for the layout.

With that in mind, I believe I may have narrowed the problem to a place in com/google/unity/ads/Banner.java, where its calling:

FrameLayout.LayoutParams adParams = new FrameLayout.LayoutParams(
            FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.WRAP_CONTENT);

  I believe the adParams should be explicitly setting the size of the adView, but in the code, it looks like adParams just inherit size from parent (in the unity player, i suspect this would just be full-screen)

Unless I'm mistaken, this would cause the adView to take the entire screen (I can only assume that the reason this doesn't occur with regular Ad Mob ads is because they use a transparent background, while our Mediation ad-source does not)

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

- Ram
