### ISSUE TITLE
Banner Resolution

### ISSUE THREAD

**Issue by just-jim** [googleads/googleads-mobile-plugins#26]
Hi, I am using this plugin on a game created in Unity3D targeted for android. Everything works fine, the only issue is that I am trying to code my app to leave a blank space in the bottom so the ad doesn't overlaps essential UI on the game. I managed to do that for most of the device resolutions, but still sometimes the resolution of the ad is unexpected. (mostly in some tablets).  Can you please tell me how exactly the dimensions of the ad banner are calculated? Thanks.

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

- Ram
