### ISSUE TITLE
TopRight

### ISSUE THREAD

**Issue by 3583Bytes** [googleads/googleads-mobile-plugins#28]
Please add the AdPosition.TopRight /  AdPosition.TopLeft  Some of my games are designed around having the banner in those positions, and now that I can't submit any more games with the previous version of AdMob as of August 1st I really need this option.  

Thanks

**Comment by rampara** [comment]
The current version of the plugin is now v2.2 and includes support for additional banner positions. If you are running Unity 5.0 you will have to delete the top-level Android manifest from the Assets/Plugins/Android folder. If you are running on older versions of Unity, replace the top-level manifest file with the one linked below.

https://drive.google.com/a/google.com/file/d/0B3mVbrRS6xpKWDQ5SGVlVUx3clU/view?usp=sharing

Ram
