### ISSUE TITLE
Landscape Interstitial Ads

### ISSUE THREAD

**Issue by ecarrera** [googleads/googleads-mobile-plugins#30]
I've implemented the plugin and everything is working fine, the only one problem that the interstitial ad doesn't show in landscape mode with the exact orientation of the device, does it is working with orientation? Or, please tell me what can I do to fix it, what file should I modify to fix the orientation? Great plugin, see ya.

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

- Ram
