### ISSUE TITLE
BannerView.cs error

### ISSUE THREAD

**Issue by MaZyGer** [googleads/googleads-mobile-plugins#33]
Assets/GoogleMobileAds/Api/BannerView.cs(22,20): error CS1502: The best overloaded method match for `GoogleMobileAds.Common.IGoogleMobileAdsBannerClient.CreateBannerView(string, AdSize, GoogleMobileAds.Api.AdPosition)' has some invalid arguments

Assets/GoogleMobileAds/Api/BannerView.cs(22,20): error CS1503: Argument `#2' cannot convert `GoogleMobileAds.Api.AdSize' expression to type `AdSize'

I have no idea how to fix it

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

- Ram
