### ISSUE TITLE
Missing Positionings

### ISSUE THREAD

**Issue by moribitotech** [googleads/googleads-mobile-plugins#34]
There are only Top and Bottom positions

Missing positions:
- TopRight, TopLeft, BottomLeft, BottomRight

Regards and thanks for good work

**Comment by rampara** [comment]
The current version of the plugin is now v2.2 and includes support for additional banner positions. If you are running Unity 5.0 you will have to delete the top-level Android manifest from the Assets/Plugins/Android folder. If you are running on older versions of Unity, replace the top-level manifest file with the one linked below.

https://drive.google.com/a/google.com/file/d/0B3mVbrRS6xpKWDQ5SGVlVUx3clU/view?usp=sharing

Ram
