### ISSUE TITLE
New Admob Support!?

### ISSUE THREAD

**Issue by timmy2702** [googleads/googleads-mobile-plugins#37]
Hi,

I've already implemented this plugin to my unity and it works well. However, I'm just wondering whether this plugin supports the new Admob or not!? Since after August 31, Google will stop the old Admob, just only the new one.

Thanks!

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

Ram
