### ISSUE TITLE
Admob not working for iOS

### ISSUE THREAD

**Issue by anum90** [googleads/googleads-mobile-plugins#40]
I am trying to create interstitial ads in unity for iOS platform. I have followed coding sample provided in GoogleMobileAdsDemoScript file, but unfortunately ads are not produced. I just see a message on console:

<Google> To get test ads on this device, call: request.testDevices = @[@"b9ade3b76dd9d16ccc6c61b78bf7d427"];

I have used following code in unity:

            private void RequestInterstitial()
	      {
		print ("Requesting AD");
	
		#if UNITY_EDITOR
		string adUnitId = "unused";
		#elif UNITY_ANDROID
		string adUnitId = "INSERT_ANDROID_INTERSTITIAL_AD_UNIT_ID_HERE";
		#elif UNITY_IPHONE
		string adUnitId = "ca-app-pub-3113890509031570/1543899246";
		#else
		string adUnitId = "unexpected_platform";
		#endif

		// Create an interstitial.
		interstitial = new InterstitialAd(adUnitId);
		// Register for ad events.
		interstitial.AdLoaded += HandleInterstitialLoaded;
		interstitial.AdFailedToLoad += HandleInterstitialFailedToLoad;
		interstitial.AdOpened += HandleInterstitialOpened;
		interstitial.AdClosing += HandleInterstitialClosing;
		interstitial.AdClosed += HandleInterstitialClosed;
		interstitial.AdLeftApplication += HandleInterstitialLeftApplication;
		// Load an interstitial ad.
		interstitial.LoadAd(createAdRequest());
	}

	// Returns an ad request with custom ad targeting.
	private AdRequest createAdRequest()
	{
		return new AdRequest.Builder ()
			.AddTestDevice(AdRequest.TestDeviceSimulator)
			.AddTestDevice("my device ID")
				.AddKeyword("game")
				.AddExtra("color_bg", "454545")
				.Build();
		
	}

	#region Interstitial callback handlers
	
	public void HandleInterstitialLoaded(object sender, EventArgs args)
	{
		print("HandleInterstitialLoaded event received.");
		interstitial.Show();
	}
	
	public void HandleInterstitialFailedToLoad(object sender, AdFailedToLoadEventArgs args)
	{
		print("*********** HandleInterstitialFailedToLoad event received with message: " + args.Message);
	}
	
	public void HandleInterstitialOpened(object sender, EventArgs args)
	{
		print("HandleInterstitialOpened event received");
	}
	
	void HandleInterstitialClosing(object sender, EventArgs args)
	{
		print("HandleInterstitialClosing event received");
	}
	
	public void HandleInterstitialClosed(object sender, EventArgs args)
	{
		print("HandleInterstitialClosed event received");
	}
	
	public void HandleInterstitialLeftApplication(object sender, EventArgs args)
	{
		print("HandleInterstitialLeftApplication event received");
	}
	
	#endregion

Please help me in resolving this issue. Thanks.

**Comment by rampara** [comment]
Closing due to non-response. If this is still an issue feel free to reach to the support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

- Ram
