### ISSUE TITLE
How to get alive ads on iOS 

### ISSUE THREAD

**Issue by TroubleXMan** [googleads/googleads-mobile-plugins#41]
I build my project to iPhone, without "AdRequest.Builder.AddTestDevice()", but I can still not get alive ad, the Xcode have a message on console: To get test ads on this device, call: request.testDevices

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

- Ram
