### ISSUE TITLE
Interstitial memory leak & performance 

### ISSUE THREAD

**Issue by cumhuronat** [googleads/googleads-mobile-plugins#43]
You should implement the destroy method of Interstitial class asap.
https://github.com/googleads/googleads-mobile-plugins/blob/master/unity/source/plugin-library/src/com/google/unity/ads/Interstitial.java#L119

On low end phones the fps drops with each interstitial ad shown. After 4-5 interstitial ads the game crashes.

**Comment by rampara** [comment]
Closed to age of issue. If this problem still exists, feel free to re-open to issue.

Ram
