### ISSUE TITLE
Button under the ad 

### ISSUE THREAD

**Issue by Jarek-K** [googleads/googleads-mobile-plugins#45]
So, I managed to integrate ads into my android game, but now i encountered another problem: I cannot click ad without clicking button behind it. And i cannot move this button because it takes almost whole screen. I tried Gui buttons, OnMouseDown, and touchposition as a button, but neither of those helped.So what can I do to end this?

Thank you

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

Ram
