### ISSUE TITLE
Google Play Games Plugin plus Ads

### ISSUE THREAD

**Issue by KamiKaze425** [googleads/googleads-mobile-plugins#46]
So I'm currently using BFS Google Play games plugin (which sadly doesn't seem to have support anymore) and this Ad plugin.
For some reason, when I add the unity-plugin-library. jar file, my app will crash on launch. However, if I don't have it, the ads will not work.
It seems like there was a problem with the google-play-services.jar from the BFSGPG plugin not being the full jar file (missing the ad folders), but when I replaced them, the app would still crash on launch.

I can't really abandon the BFS plugin or else I would...

**Comment by rampara** [comment]
Closing due to non-response. If this is still an issue feel free to reach out at the support group.

- Ram
