### ISSUE TITLE
Low framerate while using any of the ad

### ISSUE THREAD

**Issue by abrards** [googleads/googleads-mobile-plugins#48]
Hi, like suggested in this thread http://answers.unity3d.com/questions/810267/admob-highly-slowing-game-framerate.html I post the problem here.

It seems like ads are slowing my game a lot.
I created a scene only with GoogleAdDemoScript in my project, which contains other scenes.
I begin with the Demo scene and then when I press back i go back to a menu.

When I do like, creating banner/interstitial and showing them, then destroy them or not, if I go to the menu, then it is really slow.

The only thing I found which works perferctly is for banners. If I request a banner then hide it, then it is smooth everywhere.

But the thing is, I really can't use at all the ads during game otherwise it slows the framerate. The only thing I found is creating a scene especially for ads, show a banner, wait, hide it , then go back. A bit heavy... could you help please?

**Comment by rampara** [comment]
Closed due to age of issue. If this problem still exists, feel free to re-open to issue.

Ram
