### ISSUE TITLE
iOS8.1 Banner ad not displaying correctly

### ISSUE THREAD

**Issue by MaurizioFrances** [googleads/googleads-mobile-plugins#49]
Hi,

After updating a test device to iOS8.1 (an iPod 5th Gen) the Smart Banner ads are no longer displaying properly. They either don't show up at all, or appear as a blank grey box in the middle of the screen that is not stretched as smart banners should be. The interstitial ads continue to work normally.

The exact same version of the app continues to work fine on a different device (iPhone5) which is still running iOS7.1, with the ads always appearing when they are meant to and with the correct Smart Banner sizing.

Both screenshots are attached.
![ios8_screenshot](https://cloud.githubusercontent.com/assets/3476663/4711801/121ea930-58c1-11e4-845f-b3bb0f3f1d1c.PNG)
![ios7_screenshot](https://cloud.githubusercontent.com/assets/3476663/4711804/15aa18d2-58c1-11e4-963f-ea3d6c1e3b7c.PNG)

**Comment by rampara** [comment]
Closed to age of issue. If this problem still exists, feel free to re-open to issue.

Ram
