### ISSUE TITLE
Hide/Destroy/Show Functions doesn't work. What Do i need to do?

### ISSUE THREAD

**Issue by bekiryanik** [googleads/googleads-mobile-plugins#51]
Hello everyone,

As you see in the title of the issue, i have problem on call functions. I call these functions but they don't work on iOS. At the beginning of the game banner comes to screen very good. I want to destroy this banner after i hit play button. But banner doesn't destroy. Is there any problem on this plugin?

**Comment by rampara** [comment]
Closing due to non-response. If this is still an issue feel free to reach out at the support group.

- Ram
