### ISSUE TITLE
GADUObjectCache.m - ARC forbids explicit message

### ISSUE THREAD

**Issue by grosssmutttr** [googleads/googleads-mobile-plugins#52]
If I try to build the project these errors occur in GADUObjectCache.m, GADUInterstitial.m ...:

1. Semantic issue - 'release' is unavailable
2. ARC Restrictions - ARC forbids explicit message send of 'release'
3. ARC restrictions - ARC forbids explicit message send of 'dealloc'

These are the marked error lines:
void dealloc{
[_references release];
[super dealloc];
}

I'm using Xcode 6.1.
I added the libraries and the -ObjC flag
I downloaded the latest Google Mobile Ads SDK for iOS.
Tried with Google Mobile Ads Unity Plugin v2.1 -unitypackage file and also with the source files.

Perhaps this is because there is something missing for the iOS 8 support?

**Comment by Mikejinhua** [comment]
ARC  and SDK 7.0.0 both are trouble now.
