### ISSUE TITLE
Support ARC for Unity 5

### ISSUE THREAD

**Issue by ericleich** [googleads/googleads-mobile-plugins#54]
Unity 5.0 beta 9's [release notes](http://unity3d.com/unity/beta/5.0/release-notes) indicate ARC support. As Unity 5 moves out of beta, the plugin should also be updated to use ARC.

**Comment by rampara** [comment]
The current version of the plugin is now v2.2 and includes support for both Unity 5 and Google Mobile Ads SDK v7.0.0. If you are running Unity 5.0 you will have to delete the top-level Android manifest from the Assets/Plugins/Android folder.

Ram
