### ISSUE TITLE
Ads not showing up on Android Phone

### ISSUE THREAD

**Issue by Alendro305** [googleads/googleads-mobile-plugins#57]
I cannot seem to get neither Banner ads or Interstitial ads to show up on my android device using the scene/script provided. I imported the project correctly and the google play services lib. Is there anything else I could be missing?

**Comment by rampara** [comment]
This issue is being closed due to its age. For bugs in the plugin open a new issue or reach out on our support group at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

Ram
