### ISSUE TITLE
Please Help: bannerView.Hide() & bannerView.Show() does not work properly

### ISSUE THREAD

**Issue by siloni** [googleads/googleads-mobile-plugins#59]
Hi,
I am on unity 4.6.1f1. I am using this plugin to show ads. In my game I have just one scene where I am also showing the game over contents once the player dies. 
My requirement is that when the game is in progress, don't show any ads. But when, the character dies, I want to show the ads. The plugin is working extremely well showing the ads. But since I want to show the ads only when the character dies, I tried using the bannerView.Hide() method. But its not working. Basically once the ads are loaded, these are always shown and there is no way to hide them.

	void Start () {
        bannerView = new BannerView(AD_UNIT_ID, AdSize.SmartBanner, AdPosition.Top);
        request = new AdRequest.Builder().Build();
        bannerView.LoadAd(request);
        bannerView.Hide();
        //the above works. so, when the game first loads the ads are not shown
        //NOTE: The above was the suggestion by Eric in an issue raised earlier. But I am looking for an ON/OFF functionality which I have not been able to achieve so far.
	}
	
	void Update () {
        if (hit) {
	    //I have code here to show the game over text, scores etc.
            bannerView.Show();
            //the above shows the banner

        }	
        
        //this method is called when the user presses the replay button
    public void replayGame() {
        bannerView.Hide();
        //the issue is the above call does not work and when the game starts again, the ads are
        //still there. I want to hide the ads at this point so that the player does not 
        //see any ads while he is playing the game.
        
        Application.LoadLevel(Application.loadedLevel);
    
    }        

Regards,
Siloni

**Comment by ericleich** [comment]
I think you're calling `Show()` again without realizing it. Unity's `Update()` method gets called every frame. Is it possible you forgot to clear the `hit` variable, and so the add is getting shown again in the next frame when you start a new level?

**Comment by rampara** [comment]
Closing due to non-response. If this is still an issue feel free to reach out at the support group.

- Ram
