### ISSUE TITLE
Ads arent showing

### ISSUE THREAD

**Issue by SalamiBrot** [googleads/googleads-mobile-plugins#61]
I followed the guide to implement the plugin but my ads aren't showing on Android! 

Please fix, thank you!

**Comment by ericleich** [comment]
We need some more information to diagnose the issue.

What part is failing? What do the Android logs say? Are you making an ad request? If so, what is the error code?

**Comment by rampara** [comment]
Closing due to non-response. If this is still an issue feel free to reach out at the support group.

- Ram
