### ISSUE TITLE
iOS: Mediation for Facebook Audience Network don't work

### ISSUE THREAD

**Issue by Russel1** [googleads/googleads-mobile-plugins#62]
I would like to use the Admob Mediation for Facebook Audience Network in Unity.
It works great with Android, but on iOS the advertising will not be shown.

I integrated the Google Mobile Ads Unity Plugin, the libAdapterFacebook.a, the FBAudienceNetwork.framework
and included the facebook audience network configurations in admob Dashboard.

If is use the native call for Facebook Audience Network with this code, then it works:

    // Create a banner's ad view with a unique placement ID (generate your own on the Facebook app settings).
    // Use different ID for each ad placement in your app.
    FBAdView *adView = [[FBAdView alloc]
                   initWithPlacementID:@"MyPlacementID"
                   adSize:kFBAdSize320x50
                        rootViewController:((UnityAppController *)[UIApplication sharedApplication].delegate).rootViewController];
   
    // Set a delegate to get notified on changes or when the user interact with the ad.
    //adView.delegate = self;
   
    // When testing on a device, add its hashed ID to force test ads.
    // The hash ID is printed to console when running on a device.
    [FBAdSettings addTestDevice:@"TestDeviceID"];
   
    // Initiate a request to load an ad.
    [adView loadAd];
   
    // Reposition the ad and add it to the view hierarchy.
    CGRect screenRect = [[UIScreen mainScreen] bounds];
    adView.frame =
    CGRectOffset(adView.frame,
                 0,
                 screenRect.size.height - kFBAdSize320x50.size.height);
    [((UnityAppController *)[UIApplication sharedApplication].delegate).rootView addSubview:adView];

If I use the Admob Mediation, then I get this Debug Output:
    HandleAdLoaded event received.

But the advertising will not be shown.

Where is the problem?
If the facebook advertising is not rendered within the admob view?
If it is rendered outside the View? Do I need a Reposition?

**Comment by ericleich** [comment]
Interesting. If you're getting the success callback, I'm not sure why the ad wouldn't show. Would you be able to share your Unity project that shows the issue?

**Comment by Russel1** [comment]
I will share a example project on monday. Thank you!

**Comment by Russel1** [comment]
Hello Eric,

here is my example project:
https://www.dropbox.com/sh/twmvhzyxmhl4f8x/AACX726fVYhak80bV44b5osma?dl=0

You must only add the frameworks:
AdSupport
AudioToolbox
AVFoundation
CoreGraphics
CoreTelephony
EventKit
EventKitUI
MessageUI
StoreKit
SystemConfiguration

and add the -ObjC linker flag to your Other Linker Flags in Build Settings.

and you must Drag the FBAudienceNetwork.framework (Assets/Plugins/iOS) file to the Xcode project and place it under the Frameworks folder.

Now I get this debug message: "HandleFailedToReceiveAd event received with message: Failed to receive ad with error: Request Error: No ad to show from all configured ad networks", but Why? Only when I add a Device Hash Id for Facebook Test Ads with this call [FBAdSettings addTestDevice:@"5688846070b177b0c5c68f47c46cb1bd81c9a64c"], then I get "HandleAdLoaded event received.".
But the advertising will not be shown.

**Comment by ericleich** [comment]
I got the Facebook test ad when running your app, after calling FBAdSettings addTestDevice. See screenshot below. Not sure if it mattered, but I grabbed the latest Facebook adapter (version 1.0.1) from the [mediation networks page](https://developers.google.com/mobile-ads-sdk/docs/admob/ios/mediation-networks).

The reason you aren't getting an ad back from Facebook when test settings aren't on must be because Facebook hasn't enabled you for live traffic yet. And you have AdMob disabled currently on your placement, so that's why no ad networks are available.

![img_0006](https://cloud.githubusercontent.com/assets/2605332/5713886/16e5dc44-9a76-11e4-96ac-6971ea78433c.PNG)

**Comment by Russel1** [comment]
Hello Eric,

I using the latest Facebook adapter (version 1.0.1), too.

Where you added the [FBAdSettings addTestDevice:@"5688846070b177b0c5c68f47c46cb1bd81c9a64c"] call?

Can you explain your procedure in XCode? Did you us my adUnitId's for your test?

The FB Test-Advertising will not be shown on my iPhone 4S :(...

**Comment by ericleich** [comment]
I put it right [here](https://github.com/googleads/googleads-mobile-plugins/blob/master/unity/source/Assets/Plugins/iOS/GADUBanner.m#L75), at the point where the ad is about to be loaded on the iOS side. I also had to add `#import <FBAudienceNetwork/FBAudienceNetwork.h>` at the top of the file so that FBAdSettings is recognized.

I did use your ad unit ID defined in Unity, which returned Facebook as the first network and went through the Facebook adapter to show the test ad above.

**Comment by groscalin** [comment]
@ericleich 
Hi. we're working on mediation for FB audience network either,
I have some questions.. 

1. How do I know the exact version of Facebook adapter(libfacebookadapter.a) and 
   (How) Can I get(or view) this official FacebookAdapter source?

2. android seems fine, works perfectly, but on iOS
   - SmartBanner request doesn't work, (it says 'no ad to show'), but explicit 320x50 banner size just works on iPhone
   - on iPadmini, both size(smart banner + 320x50) didn't work at all.

We use unity4.5.x + admob6.12.2(iOS) + 'GoogleMobileAds for Unity' with the [FBAdSettings addTestDevice:@"XXXX"]  calls.

thanks..

**Comment by ericleich** [comment]
When you download the FB adapter and open the zip, the folder is versioned.

The FB adapter source is not publicly available.

Same question as for the OP, could you provide a sample Unity project I could run myself to verify?

**Comment by dklt** [comment]
responding to old issue, 
FB wont serve ad when

1. idfa is disabled or,
2. testflight build, when idfa keeps changing for every HTTP request.

**Comment by rampara** [comment]
This issue tracker is for issues pertaining to the Google Mobile Ads Unity plugin. The issue you're describing is one related to Facebook Ad Network serving.
