### ISSUE TITLE
Ads not initialized on iOS

### ISSUE THREAD

**Issue by LionbI4** [googleads/googleads-mobile-plugins#63]
When Interstitial ad is tried to load sdk returns error: 
game [240:60b] <Google:HTML> You are currently using version 6.10.0 of the SDK, which doesn't officially support iOS 8. Please consider updating your SDK to the most recent sdk version, 6.12.2, to get iOS 8 support, including a fix for smart banner rendering in landscape mode. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/mobile-ads-sdk/docs/admob/ios/rel-notes.

I downloaded from here https://developers.google.com/mobile-ads-sdk/download and added 6.12.2 admob sdk to xcode but error still exist

**Comment by LionbI4** [comment]
Not to mention, that iOS version of my device is 7.1.2

**Comment by ericleich** [comment]
If you downloaded and included 6.12.2 but the SDK is still reporting that you're using 6.10.0, then there's still some reference to 6.10.0 in your project that's causing 6.10.0 to be built in instead of 6.12.2. In your build settings, check the Library Search Paths and remove any references to the 6.10.0 SDK.

**Comment by LionbI4** [comment]
I never downloaded 6.10 ... So i don't have it

**Comment by ericleich** [comment]
Do you have a sample project I could look at that reproduces the issue?

Other things to note:
1. This message is coming from the Mobile Ads SDK, not the Unity plugin.
2. The message is just a warning that always gets logged if the version is less than the latest one, regardless of device. The SDK will still return ads. Basically, it's just encouraging you to upgrade your SDK.
