### ISSUE TITLE
Wrong interstitial orientation for iOS8

### ISSUE THREAD

**Issue by erennsahinn** [googleads/googleads-mobile-plugins#64]
We are using Unity 4.6.0. Our game has scenes on both orientations, some scenes are portrait, others are landscape; but same scene does not support both orientations. When we try to display interstitial on a landscape scene on iOS8, ad is displayed on wrong orientation. Is there anything we can do about it ? 
![img_5045](https://cloud.githubusercontent.com/assets/6987968/5703275/4ed2d7aa-9a6d-11e4-89ac-515242129091.PNG)
![img_5046](https://cloud.githubusercontent.com/assets/6987968/5703279/569d9c04-9a6d-11e4-9634-e0129befa995.PNG)

**Comment by ericleich** [comment]
Are you requesting the interstitial in a portrait scene, and showing it on a landscape scene? If so, you should reload an interstitial when you change to a landscape scene and vice versa.

**Comment by rampara** [comment]
Closing due to non-response. If this is still an issue feel free to reach out at the support group.

- Ram
