### ISSUE TITLE
BannerView.Destroy() and Hide() don't work with Unity 4.6.1p4

### ISSUE THREAD

**Issue by Russel1** [googleads/googleads-mobile-plugins#65]
BannerView.Destroy() and Hide() don't work with Unity 4.6.1p4 for Android, but on Unity 4.5.5 it works.

**Comment by PAHeartBeat** [comment]
Hi @Russel1 

I am using same version of Unity3D pro, in my game banner will hide on calling function BannerView.Hide() method

Please check my learning project from GitHub repo, URL: https://github.com/PAHeartBeat/Unity-GoogleMobileAds
