### ISSUE TITLE
Unity 4.6.1p4 broke interstitial video ads in iOS 7/8

### ISSUE THREAD

**Issue by azurehawk** [googleads/googleads-mobile-plugins#66]
After updating to Unity 4.6.1p4, sometimes the ads shows only black screen with close button on the top right but it cannot be pressed. After pressing the home button in iOS device and then reopen the app, the ads will hide automatically and the app run as usual. After doing some troubleshooting, I found that it is the video ads that cause trouble, text and image ads work normally. I don't know what Unity has changed in 4.6.1p4 but it seems the video player part is broken. Maybe you could shed some light about this problem? For now, I just have to disable the video ads to make sure the ads shown properly.

**Comment by PAHeartBeat** [comment]
Hi @azurehawk 

I am using Unity 4.6.1p with with XCode 6.1.1 and iOS Base SDK 8.1 all ads shows and button works perfactly.

Please check it once differant xcode and lateste Unity version 4.6.2p1 or Unity 4.6.1p5 (both are support  arm64)

I also advice to check device oriantation if your game support landscape as well as portrait both oriantation may you face that isssue. If your game support both oriantation try lock oriatation with anyone but support auto rotation. 

I hope you find actual problem which cause issue for video ads.

**Comment by DavidSkeppstedt** [comment]
@azurehawk @PAHeartBeat: I am also facing this issue but with regular interstitial ads... It occurs only when on Wifi which is strange! I wonder which version of the googleads sdk you use? I am on 6.12 and I think that it could cause problems...

**Comment by PAHeartBeat** [comment]
Hi @DavidSkeppstedt 

Right now, I am using AdMob iOS SDK 7.0.0, but I have also tested it with AdMob iOS SDK 6.12.2, it was works fine for me using iOS SDK 6.12.2. 

I have little modified few files for iOS 7.0.0.

We are using WiFi connection to test it. However we didn't try it with 2G (GPRS / EDGE) connection or with 3G / LTE base highspeed mobile internet connection.

I don't think SDK has any issue with internet connection speed / bandwith. if user / developer using low bandwith / low speed connection. SDK will take more time to cacheInterstitial ad, I thought you have to listen callback events from SDK, so you can get proper reson about why ads are not getting.

Thanks

**Comment by rampara** [comment]
Closing since this isn't a bug in the plugin or a feature request. For further support please reach out to us on our forum.

- Ram
