### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Cryptomane** [googleads/googleads-mobile-plugins#67]
Greetings,

I need to add this plugin in my project, but there seem to be missing files.

There is no "GoogleMobileAdsPlugin.unitypackage" file and the sample project is missing all the plugin structure.

In the README files you assume we already have that package, but where can I find it?

**Comment by ericleich** [comment]
There is a GoogleMobileAds.unitypackage in the releases page of this repo. You can import that package into Unity and it contains all the files you need.

**Comment by PAHeartBeat** [comment]
Hi Cryptomane,

you can also my test project which are working in both paltform (iOS and Android) But I want to clear a thing, I have modified few Script as my requirement. you can try it. here is link of GitHub repo https://github.com/PAHeartBeat/GoogleAdsUnity.git

**Comment by Cryptomane** [comment]
Found it, thank you.
