### ISSUE TITLE
Fix plugin for Google Mobile Ads SDK iOS 7.0.0

### ISSUE THREAD

**Issue by ericleich** [googleads/googleads-mobile-plugins#68]
Version 7.0.0 of the iOS SDK breaks the plugin. The imports have changed due to SDK being released as a framework, and it makes use of a couple methods that have been removed/renamed, such as GADAdMobExtras.

**Comment by PAHeartBeat** [comment]
Hi Eric,

I am not XCode or iOS Developer but I face issue as you explain here, to cure that I modified few .h and .m files from unity package iOS Folder as bellow

**File: *GADURequest.m*** 
Old Data for Hader imports for iOS SDK 6.12.0
`#import "GADAdMobExtras.h"
#import "GADRequest.h" 
#import "GADURequest.h"`
change with for iOS SDK 7.0.0

`#import "<GoogleMobileAds/GADExtras.h>"
#import "<oogleMobileAds/GADRequest.h>" 
#import "GADURequest.h"`


and old RequestMethod for iOS SDK 6.12.0
`- (GADRequest *)request {
  GADRequest *request = [GADRequest request]; 
  request.testDevices = self.testDevices; 
  request.keywords = self.keywords; 
  request.birthday = self.birthday; 
  request.gender = self.gender; 
  [request tagForChildDirectedTreatment:self.tagForChildDirectedTreatment]; 
  [self.extras setValue:@"1" forKey:@"unity"]; 
  GADAdMobExtras *extras = [[[GADAdMobExtras alloc] init] autorelease]; 
  extras.additionalParameters = self.extras; 
  [request registerAdNetworkExtras:extras]; 
  return request; 
}`
with 4th last line change for iOS SDK 7.0.0

`- (GADRequest *)request {
  GADRequest *request = [GADRequest request];
  request.testDevices = self.testDevices;
  request.keywords = self.keywords;
  request.birthday = self.birthday;
  request.gender = self.gender;
  [request tagForChildDirectedTreatment:self.tagForChildDirectedTreatment];
  [self.extras setValue:@"1" forKey:@"unity"];
  GADExtras *extras = [[[GADExtras alloc] init] autorelease];
  extras.additionalParameters = self.extras;
  [request registerAdNetworkExtras:extras];
  return request;
}`

**File: *GADUBanner.m***
Old Data for Hader imports for iOS SDK 6.12.0

`#import "GADUBanner.h"

#import "GADAdMobExtras.h" 
#import "GADAdSize.h" 
#import "GADBannerView.h" 
#import "GADBannerViewDelegate.h"`

Changes with for iOS SDK 7.0.0

`#import "GADUBanner.h"

#import "<GoogleMobileAds/GADExtras.h>"
#import "<GoogleMobileAds/GADAdSize.h>"
#import "<GoogleMobileAds/GADBannerView.h>"
#import "<GoogleMobileAds/GADBannerViewDelegate.h>"`


But some how My xCode not able to find **GADExtras.h** file from famework **GoogleMobileAds.framework** of iOS SDK 7.0.0, in GADURequest.m file, its gave me xcode error like ![screen shot 2015-02-06 at 11 09 51 am](https://cloud.githubusercontent.com/assets/4506923/6075129/970e46f6-adf2-11e4-951d-eb64807e2e80.png)

Can you guide me what I am doing wrong,

~Thanks
Ranpariya Ankur (PAHeartBeat)

**Comment by ericleich** [comment]
You don't need the quotes around `#import <GoogleMobileAds/GADExtras.h>`. Another neat trick with the 7.0.0 update is you can just the single line `@import GoogleMobileAds;` and it'll pull in all the relevant classes for you.

**Comment by PAHeartBeat** [comment]
Hi Eric,

Thanks for you valueable feedback, I used first option `#import <GoogleMobileAds/GADExtras.h>` and it's now it will working.

I have change this files as given bellow

File: *GADURequest.m* 
`#import <GoogleMobileAds/GADExtras.h>`
`#import <GoogleMobileAds/GADRequest.h>`
`#import "GADURequest.h"`

`- (GADRequest *)request {`
`GADRequest *request = [GADRequest request];`
`request.testDevices = self.testDevices;`
`request.keywords = self.keywords;`
`request.birthday = self.birthday;`
`request.gender = self.gender;`
`[request tagForChildDirectedTreatment:self.tagForChildDirectedTreatment];`
`[self.extras setValue:@"1" forKey:@"unity"];`
`GADExtras *extras = [[[GADExtras alloc] init] autorelease];`
`extras.additionalParameters = self.extras;`
`[request registerAdNetworkExtras:extras];`
`return request;`
`}`

File: *GADUBanner.m*
`#import "GADUBanner.h"

`#import <GoogleMobileAds/GADExtras.h>`
`#import <GoogleMobileAds/GADAdSize.h>`
`#import <GoogleMobileAds/GADBannerView.h>`
`#import <GoogleMobileAds/GADBannerViewDelegate.h>`


File: *GADUInterstitial.m*
`#import "GADUInterstitial.h"`

`#import <GoogleMobileAds/GADExtras.h>`
`#import <GoogleMobileAds/GADAdSize.h>`
`#import <GoogleMobileAds/GADInterstitial.h>`
`#import <GoogleMobileAds/GADInterstitialDelegate.h>`


File: *GADRequest.h* (<<AdMobSDKFolder>>/GoogleMobileAds.framework/Headers/)
Add this two line and save hader file after `@protocol GADAdNetworkExtras;` line (without single quote)
`// Add this constant to the testDevices property's array to receive test ads on the simulator.`
`#define GAD_SIMULATOR_ID @"Simulator"`



I also made few changes in file *GADUInterstitial.m* and *GADUInterstitial.h* to pause unity in backend at time of interstitial is present in screen. (regarding that I have created a new Isssue #69)
Thanks a lot Eric,

**Comment by mitralone** [comment]
Any progress? If not, can I have link to previous version downloads?

**Comment by trungdq88** [comment]
Dear Eric,
Do we have any update? Or temporary fix guide for this problem?

**Comment by PAHeartBeat** [comment]
@trungdq88 

Please check my last comment, it's currently work for me in Unity 4.6.1p5 (using mono and IL2CPP backend) yet no issue I faced in my test project. this is temp. solution (not offical) for AdMob iOS 7.0.0, otherwise you can use AdMob iOS SDK 6.12.2

**Comment by trungdq88** [comment]
@PAHeartBeat 
I get this error after following your changes:
![screenshot 2015-02-24 20 00 38](https://cloud.githubusercontent.com/assets/4214509/6349716/db3527ca-bc5f-11e4-919f-6eab3db3f01d.png)

Do you have any idea? I am running my project on Unity 4.6.2f1, Xcode 6.1.1, GoogleMobileAdsSdkiOS-7.0.0 and latest release of [GoogleMobileAds.unitypackage (2.1)](https://github.com/googleads/googleads-mobile-plugins/releases)

**Comment by xzodia** [comment]
@trungdq88 You can fix that by changing it to #import <GoogleMobileAds/GADRequest.h> and moving the Versions/A/Headers folder and Versions/A/GoogleMobileAds file to the root of the SDK directory. (you can remove the rest of the files and folders)

**Comment by PAHeartBeat** [comment]
Hi @trungdq88,

That missing file is in side of AdMob iOS SDK (not in Unity Wrapper for AdMob SDK by Gogole). So I think you has forget about add AdMob iOS SDK in your XCode folder.

You have to download iOS SDK from Google AdMob SDK Page and need to add manualy in your xcode proect (exported from your unity project) as instruction given in this link (https://developers.google.com/mobile-ads-sdk/docs/admob/ios/quick-start#manually_using_the_sdk_download)

**Comment by trungdq88** [comment]
@PAHeartBeat @xzodia  I actually added AdMob iOS SDK, I have just changed the link to `#import <GoogleMobileAds/GADRequest.h>` and the error is gone but I got a new error:

![screenshot 2015-02-25 13 14 00](https://cloud.githubusercontent.com/assets/4214509/6365927/0363407e-bcf1-11e4-8170-3a0748aef295.png)

Looks like a simple syntax error, I tried to put the brackets in several places but cannot fix it (I am new to Xcode). Can you help me with that?

**Comment by PAHeartBeat** [comment]
Hi @trungdq88,

I not faced this error when I am trying. I just have small guess about it.

I thought you removed this line by mistke 
`#import "UnityAppController.h"`

or you can try this one

Google AdMob Team have updated (may a or two day ago) Unity Wrapper for iOS SDK 7.0.0, may be you are using that one and also implimenting changes which I have suggest.

if you using old AdMob Wrapper which works good witht iOS SDK 6.12.2, please check My test project on GitHub.

In that test project you have to just do one thing after insert iOS SDK 7.0.0. in xcode project open bellow given file and add these two line
`File: GADRequest.h (SDKFolder/GoogleMobileAds.framework/Headers/)`
Add this two line and save hader file after `@protocol GADAdNetworkExtras;` line (without single quote)
`// Add this constant to the testDevices property's array to receive test ads on the simulator.`
`#define GAD_SIMULATOR_ID @"Simulator"`

**Comment by ericleich** [comment]
https://github.com/googleads/googleads-mobile-plugins/commit/a61927391a9a6a571bdcbaffbf5dbc1f8e9830ad added support for iOS 7.0.0. Right now you'll need to grab the source files from the repo in Assets/Plugins/iOS, and replace them with the current files in your app.

Also in your Xcode project, you'll want to make sure that "Enable modules" and "Link frameworks automatically" are both set to "Yes" in your build settings.

**Comment by trungdq88** [comment]
Thanks everyone,
I am able to build my project now.

**Comment by paradizIscool** [comment]
Hi everyone,

I have "Module 'GoogleMobileAds' not found" error, I enabled modules and frameworks are automatically link.

**Comment by MaraZahidulin** [comment]
Hi. 
SDK 7 on XCode 6.1 doesn't work. Have errors:
 "umbrella header "GoogleMobileAds.h" not found"
"could not build module GoogleMobileAds"

Can you help me please.

**Comment by KyDenZ** [comment]
Hello,

I think you have a problem with the emulation ID.
I want to know how to pouur settle this problem, and if once this problem is resolved, the publicicté will be functional on all iphones
![sans titre-1](https://cloud.githubusercontent.com/assets/7247673/6446766/6f794aea-c10d-11e4-828a-1991b4abed73.jpg)
![sans titre-2](https://cloud.githubusercontent.com/assets/7247673/6446767/6f7c1c66-c10d-11e4-9166-1593f0d0fd6c.jpg)

thank you

**Comment by siddharth3322** [comment]
I found similar issue using latest admob plugin sdk. I have uploaded image that demonstrate some what my xcode log details.

I am using Unity 4.5.5p3 version to create for xCode build. Also I have used xCode 6.1 installed.
I have tried above all post content in my project but didn't get success in that.

Please give some suggestion where I was doing wrong.

![screenshot 2015-03-26 13 29 47](https://cloud.githubusercontent.com/assets/3082151/6863445/698ec79a-d477-11e4-9797-2fac521afa61.png)

**Comment by MaraZahidulin** [comment]
Solution: https://github.com/googleads/googleads-mobile-plugins/issues/77

**Comment by ranjitk-plackal** [comment]
Hello All, I am getting error Module 'GoogleMobileAds' not found when I use @import GoogleMobileAds;

**Comment by rampara** [comment]
Have you enabled modules in your project settings?

- Ram

**Comment by ranjitk-plackal** [comment]
yes @rampara

**Comment by ranjitk-plackal** [comment]
Hello @ericleich @PAHeartBeat @trungdq88 I am not able to get it working, I am using interstial and banner ads both in my app, if I comment out interstial related code, my app builds properly, but if I uncomment interstitial retlated code, I get error saying Parse issue:Module 'GoogleMobileAds' not found when I use @import GoogleMobileAds; But before this while using SDK 12.12, I used to not get any error. Also the sample app given my google for interstitial doesnt build and gives same error.

**Comment by malokuS** [comment]
Hello @ranjitk-plackal ... Did you managed to fix this issue ? - as i have the same problem which is driving me crazy ...

Thanks 

malokuS

**Comment by ranjitk-plackal** [comment]
I have removed pods completely and I am doing it manually @malokuS

**Comment by malokuS** [comment]
Thank you @ranjitk-plackal , finally managed to get it working.

Best wishes ,

malokuS

**Comment by ranjitk-plackal** [comment]
@malokuS weclome, how did you got it working. Please share.

**Comment by malokuS** [comment]
Ok @ranjitk-plackal , this was my case :

I made a game with unity , so what i did was : 
      
- I re-imported the Google Mobile Ads API's(Folder which is found under : googleads-mobile-plugins/tree/master/unity/source/Assets) and the plugin too , after that  in unity I build the xcode project. Then on xcode added the GoogleMobileAds.framework on build phases and switched Enable modules(C and Objective C)  to : >  yes ... everything is working perfectly now ...

I don't know if you had the same procedure like me , but make sure to import the framework on xcode otherwise soft links can mess up and build will fail.

**Comment by ranjitk-plackal** [comment]
@malokuS thanks :)

**Comment by malokuS** [comment]
you're welcome , hopefully it's working for you too @ranjitk-plackal 

Best regards ,

malokuS

**Comment by Emils72** [comment]
HI all,

I have the same problems . 3 days stuck on this up top now. 
Just banging the head against the wall... :(
I'm actually utilizing Unity3d 5.0.1.

@malokuS : I'm sorry - I really cannot understand the steps you provided.
Let's see if it matches :
1) I imported GoogleAdMob unity package 2.2.1 in unity3d - even though I did not get the part "...re-imported the Google Mobile Ads API's(Folder which is found under : googleads-mobile-plugins/tree/master/unity/source/Assets)..."

2) Built xCode proj for iOS from Unity

3) configured in the build phases in xCode

4) in XCode switched Enable modules(C and Objective C) to : > yes 

5) Run... BAM! Still doesn't work. 
Still have 
... /Libraries/Plugins/iOS/GADUInterface 1.m:5:9: 'GADRequest.h' file not found
and
... /Libraries/Plugins/iOS/GADUInterstitial.m:9:9: 'GADAdMobExtras.h' file not found

please help me - what am I doing wrong???

**Comment by dothanhlam** [comment]
@Emils72 : I am facing the same problem as exactly your. (Unity 5.0.1, GoogleAdMod for Unity 2.2.1, GoogleMobileAds framework 7.2.1). Actually, Google Admob was working well with Unity 4.6.x, GoogleMobileAds 6.12.2 before). I also followed this thread for a month, but it's still impossible to fix this issue.

**Comment by rampara** [comment]
@Emils72 @dothanhlam You should not have to re-import the Google Mobile Ads API. We have a quick start for integrating our Unity plugin in linked at https://developers.google.com/mobile-ads-sdk/docs/games#unity. When you say you "configured the GoogleMobileAds.framework (v7.2.1) in the build phases in xCode" are you manually importing the SDK into your Xcode project?

- Ram

**Comment by Emils72** [comment]
Hi rampara, dothanhlam,

thanks for replying.
@rampara see image attached for explanation (this is what I understood...)
![frameworksetup](https://cloud.githubusercontent.com/assets/12281579/7509465/48a9aae2-f491-11e4-9174-3ed2968ed970.jpg)

Regards,
 Emils

**Comment by Emils72** [comment]
So, in the end looks like I almost made it. 
I just deleted the googleMobileAds plugin installation in Unity3d (5.0.1) and reinstalled it with latest version 2.2.1.
Then I rebuilt selecting simulator SDK in player settings (otherwise you're going to have static linking problems afterwards in xcode due to libIphone-lib.a compatibility).
Then open up xcode, follow usual instructions (add GoogleMobileAds.framework, Enable loadmodule in build settings, select armv7 arc only, in Build Phases -> Compile Sources and set flag -fno-objc-arc on all "GAD" files). 
Et voilà!
now I'm going to understand why it hangs during following simulator execution, but I did it at least through with compiling, it seems... next step to come!

Regards,
 Emils.

**Comment by dothanhlam** [comment]
@rampara , @Emils72 : I still could not build the project whatever following exact the instruction. I will try the steps from @Emils72 later, but I must temporary remove "Google Admob" for working with another features. Thanks

**Comment by mitralone** [comment]
Hello,

I believe you are only doing 1st part of import.  There is also a part
where you need to import into xcode and then do the enable .... part.
Importing only to unity will not work.

Tufan

**Comment by energo** [comment]
check my answer.
http://stackoverflow.com/a/32312920/1435700

**Comment by vanshikakapoor** [comment]
@rampara @mitralone @dothanhlam 
![screen shot 2016-02-11 at 12 54 05 pm](https://cloud.githubusercontent.com/assets/17190546/12999122/a759a20a-d171-11e5-8330-fc430f753f8d.png)

I have downloaded the latest unitypackage i.e Google Mobile Ads Unity Plugin v3.0.1 and I am using xcode 7 and unity 5.3.2 but everytime I got the error of GoogleMobileAds not found. Before that I have used 5.1 unity and encounter the same problem. I am attaching the screenshots. Please help. 
![screen shot 2016-02-11 at 1 02 20 pm](https://cloud.githubusercontent.com/assets/17190546/12999125/b7985f58-d171-11e5-8a9b-fa710fb86677.png)


Regards,
Vanshika

**Comment by rampara** [comment]
If you do not have CocoaPods installed, you will have to manually import the Google Mobile Ads iOS SDK into your Xcode project, as you did in past versions of the plugin.

**Comment by vanshikakapoor** [comment]
@rampara 

I have already done that. Yet no success. I have added all the frame frameworks and manually imported Google Mobile Ads iOS SDK (GoogleMobileAdsSdkiOS-7.6.0) and followed all the instructions. 

Regards,
Vanshika

**Comment by siddharth3322** [comment]
@vanshikakapoor, In my game admob ads for iOS working perfectly.
I have this kind of code in GADURequest.m file.

`// Copyright 2014 Google Inc. All Rights Reserved.

@import Foundation;
@import GoogleMobileAds;

#import "GADURequest.h"

@implementation GADURequest

- (id)init {
  self = [super init];
  if (self) {
    _testDevices = [[NSMutableArray alloc] init];
    _keywords = [[NSMutableArray alloc] init];
    _extras = [[NSMutableDictionary alloc] init];
  }
  return self;
}

- (void)addTestDevice:(NSString *)deviceID {
  [self.testDevices addObject:deviceID];
}

- (void)addKeyword:(NSString *)keyword {
  [self.keywords addObject:keyword];
}

- (void)setBirthdayWithMonth:(NSInteger)month day:(NSInteger)day year:(NSInteger)year {
  NSDateComponents *components = [[NSDateComponents alloc] init];
  components.month = month;
  components.day = day;
  components.year = year;
  NSCalendar *gregorian = [[NSCalendar alloc] initWithCalendarIdentifier:NSGregorianCalendar];
  self.birthday = [gregorian dateFromComponents:components];
}

- (void)setGenderWithCode:(GADUGender)gender {
  switch (gender) {
    case kGADUGenderMale:
      self.gender = kGADGenderMale;
      break;
    case kGADUGenderFemale:
      self.gender = kGADGenderFemale;
      break;
    default:
      self.gender = kGADGenderUnknown;
  }
}

- (void)setExtraWithKey:(NSString *)key value:(NSString *)value {
  [self.extras setValue:value forKey:key];
}

- (GADRequest *)request {
  GADRequest *request = [GADRequest request];
  request.testDevices = self.testDevices;
  request.keywords = self.keywords;
  request.birthday = self.birthday;
  request.gender = self.gender;
  request.requestAgent = @"unity";
  [request tagForChildDirectedTreatment:self.tagForChildDirectedTreatment];
  GADExtras *extras = [[GADExtras alloc] init];
  extras.additionalParameters = self.extras;
  [request registerAdNetworkExtras:extras];
  return request;
}

@end`

I hope this become useful to you.

**Comment by rampara** [comment]
@vanshikakapoor does the 'framework search paths' setting under build setting include the location of the Google Mobile Ads iOS SDK?

**Comment by vanshikakapoor** [comment]
@siddharth3322 

My file is same, yet no success.

**Comment by siddharth3322** [comment]
@vanshikakapoor, I can help you in this because I have integrated same thing a month ago but at present I am so much busy in game. So when I become free, I post more details regarding my project so that you can compare with yours :)

**Comment by vanshikakapoor** [comment]
@siddharth3322 I have integrated Google admobs before 15 days before in my another game, but now its giving me headache.

@rampara  I have added the path as well

**Comment by siddharth3322** [comment]
@vanshikakapoor, Which other plugins exist into your game?
It totally depend on this as well.

**Comment by vanshikakapoor** [comment]
@siddharth3322 Flurry

**Comment by siddharth3322** [comment]
@vanshikakapoor, are you getting above image error, right?

**Comment by rampara** [comment]
@vanshikakapoor If you can provide a link to a Xcode project where this error is reproducible, it can help me investigate further.

**Comment by vanshikakapoor** [comment]
@rampara  here is my full xcode project. https://www.dropbox.com/s/wpv0regmxsmb6ny/dotiOS.zip?dl=0

**Comment by rampara** [comment]
@vanshikakapoor your project referenced the Google Mobile Ads framework but did not include it under any of paths listed under 'framework search paths'. Once I added the framework to your project, I was able to build and run without issue. Adding a framework to your Xcode project on newer versions of Xcode will not automatically update your 'framework search paths'. You will have to update your build setting manually, or copy the framework to one of the paths already listed  'framework search paths'.

**Comment by vanshikakapoor** [comment]
@rampara  Can you please enlighten me more about this. If you can share some screenshots it will be great help .

**Comment by rampara** [comment]
The 'framework search paths' set for your target only included the following: 

<img width="526" alt="screen shot 2016-02-25 at 11 10 00 am" src="https://cloud.githubusercontent.com/assets/11047881/13331036/74995a9c-dbb0-11e5-90ad-e23208118e08.png">

At those paths, your project did not include the Google Mobile Ads framework. An easy solution would be to remove the framework and re-add it (but ensure to set the 'copy items if needed' setting as shown below)

<img width="497" alt="screen shot 2016-02-25 at 11 12 28 am" src="https://cloud.githubusercontent.com/assets/11047881/13331119/e4a91052-dbb0-11e5-9702-12557601dcf9.png">

**Comment by ourangzeb** [comment]
Hi every body i removed the cocoa pods using 
https://github.com/CocoaPods/cocoapods-deintegrate

I downloaded the google ad mob framework from 7.7 and then integrate it manually in the iOS project it is working perfect now.

**Comment by eholyat** [comment]
rampara, please deintegrate with cocoapods.

**Comment by AnshulPlayBuff** [comment]
@ourangzeb 
I am facing a same issue. Can you please provide a link how to integrate google mobile sdk for unity manually.
Thanks

**Comment by rampara** [comment]
If you do not want to use Cocoapods (which is the recommended approach for including the GMA SDK) you can include the [iOS GMA SDK](https://developers.google.com/admob/ios/download) within the `Assets/Plugin/iOS` directory of your Unity project or add the framework to the Xcode project generated by Unity.
