### ISSUE TITLE
Interstitial will not pause game at its present on screen

### ISSUE THREAD

**Issue by PAHeartBeat** [googleads/googleads-mobile-plugins#69]
Hi Eric,

I don't know this will a bug / feature request.

1. In iOS SDK 7.0.0 after click on interstitial Ad it's call Interstitial will left Application event but when we came back to application from app store it will not closed automatic and still present on screen. So As User Click on Ads and AdMob will redirect to app store from application so Ad will close and destroy from memory.

2. When any interstitial ad present on screen Unity Game still ruining in back of Ad View., Right now I have modified `GADUInterstitial.m` and `GADUInterstitial.h` for that and call `UnityPause(true)` at `show()` method if `isReady()` method return true,  and call `UnityPause(false)` when `interstitialDidDismissScreen` will complete.

3. On Point 2 I have manually manage with alter GoogleAdMob Unity Plugin's iOS Code. So after that when on interstitial ad will present on screen unity will pause in back and on close it will resume, but after Interstitial ad will present on screen and user will click on install `interstitialWillLeaveApplication` is call and app moves background and App Store will Open. Now when user Back to game Interstitial ad will be there on screen but Unity Resumes in back of add.

	I drill down how it will happen? I found `UnityAppController.mm` file will manage it will manage it using a bool field `_didResignActive` and two methods `applicationWillResignActive` 'n' `applicationDidBecomeActive`.

	Method will `applicationWillResignActive` when app move background and set a field `_didResignActive = true;`

	Method `applicationDidBecomeActive` will call when app get foreground, at time Unity will check ``_didResignActive` if value true, unity will self call `UnityPause(false);`

	Now when user came back on game, Our interstitial ad still there on screen but Unity has resume his self and now game will work on his Business Logic / Game Logic.

4. this point is should be as feature request. Right Now we can close / hide banner ads using `Hide()` method on `BannerView` Class from code, but there are no similar method for Interstitial ad. We expect few more method for class `InterstitialAd`
	1. `IsInterstitialPresentOnScreen(adUnitID)` this method will return `bool` value indicate is Interstitial Ad present on on screen or not, on that we can identify any circumstance we need to force hide / close Interstitial Ad.
	2. `Hide()` or `Close()` this method will close view of Interstitial from screen and than behave like user has clicked on Close button from Interstitial Ad (it will call both event `interstitialWillDismissScreen` and `interstitialDidDismissScreen`, and destroy its reference from memory)

I have Pushed current Uniyt project with Google Ad SDK v7.0.0  for iOS, you can check `GADUInterstital.m` and `GADUInterstitial.h` files commit link https://github.com/PAHeartBeat/Unity-GoogleMobileAds/commit/bd314b8b7966d277768c69bb7ff0af01eab0ef87

Thanks

**Comment by rampara** [comment]
Hi Ranpariya,

At this time we are not planning to implement pausing a Unity application while an interstitial is being shown. There are a variety of event handlers for interstitials (ie. HandleInterstitialOpened, HandleInterstitialClosed) in the plugin and pausing an application can be implemented on the Unity side by developers as required.

**Comment by PAHeartBeat** [comment]
Hi Rampara,

I can understand, about your replay about Unity Application Pause at time of Interstatial present on screen. Like each game have diffrenct senario of showing ads on screen,so force pause unity application on each / every interstitail will not good option from SDK developer side.

but what about point 1. Interstatil will not close on click on install button / clickalbe area which moves user to ad releted app / game on App Stroe., Here gamer need to add thier extra efforts to close ads after came back from appstore.

**Comment by rampara** [comment]
Interstitial not closing after being clicked is an implementation detail at the Mobile Ads SDK level, and not something the plugin or the user can control, unfortunately.
