### ISSUE TITLE
All plug-ins in one archive

### ISSUE THREAD

**Issue by koljanich** [googleads/googleads-mobile-plugins#71]
Could You give a link to comlete work Unity project (for now)? I download this project, unity asset, include in project Google play services, put my ID's (Banner and Interstitial), compile (with no errors) - and nothing! The any button not work! Please give me a complete work project or prefab.

**Comment by kimcollin** [comment]
Not sure wat u mean?

kim

**Comment by koljanich** [comment]
Unity project with all Plug-ins, components and other. For AdMob.

**Comment by koljanich** [comment]
Anybody home?

**Comment by rampara** [comment]
A basic Unity project that displays a banner ad is linked below.

https://drive.google.com/file/d/0B2oE3iOknPmMMFByUEY2Yl9DRm8/view?usp=sharing

**Comment by koljanich** [comment]
Thank you so much! Everything works, advertising is displayed in full screen!
