### ISSUE TITLE
Destroy Banner/Interstitial ads of AdMob?

### ISSUE THREAD

**Issue by simsis3d** [googleads/googleads-mobile-plugins#72]
I have a banner which only needs to be shown in main menu. And I want to show interstitials whenever player finish the game and about to return back to mainmenu. There is no problem for requesting and showing ads. However, google says me that

"When you are finished with a BannerView or InterstitialAd, make sure to call the Destroy() method before dropping your reference to it.
 
 bannerView.Destroy();
 interstitial.Destroy();
 
 This notifies the plugin that the object should be garbage collected. Failure to call this method will result in memory leaks."

I dont know when I should destroy my ads? Eachtime player exit game (For banner)? Eachtime player goes from mainmenu to game (For banner)? Should I destroy interstitials after showing it and request back when I want to show again?

**Comment by rampara** [comment]
You should call the Destroy() method on bannerViews and interstitials when you are no longer going to use them or are going to lose reference to them. You can use a single bannerView or interstitial to show multiple ads without calling Destroy() if you maintain a reference to them.
