### ISSUE TITLE
bannerview.hide () doesn't work.

### ISSUE THREAD

**Issue by pumpkinotto** [googleads/googleads-mobile-plugins#74]
hi,
i'm using the admob plugin for unity 4.6, i've implemented the banner and in game it is shown.
i have written 

**void YYYYY
if(Show == false)
        bannerview.hide();
else
        bannerview.show();
void XXXXX
if(application.loadedlevelname == XXXX)
         show = false;**

when i run the project on pc when i load the XXXX scene in the debug console appear "Dummy HideBannerView" but when i run the app on my phone the banner doesn't hide.
any ideas?
thanks

**Comment by rampara** [comment]
The "Dummy HideBannerView" debug message only appears when running the Unity application through the editor. Since there is no ads SDK available for the editor a dummy client is used with no actual functionality. The show() and hide() commands should work correctly when run on a phone. Can you see a "Calling hide() on Android" message in logcat?

- Ram

**Comment by pumpkinotto** [comment]
well,
how to use logcat?
i connect the device and start "adb" from C:\Users\user\AppData\Local\Android\sdk\platform-tools
but appear a console(cmd) for few second and then it disappear.
i'm doing something wrong, what?
thanks

**Comment by rampara** [comment]
Follow the instructions at http://developer.android.com/tools/device.html to ensure your device is correctly set up for adb debugging. When you run the adb devices command you should see your device listed. Once your device is listed run the following command 

Adb logcat GoogleMobileAdsUnityPlugin:* *:S

Whenever you hide or show a banner you should see a corresponding output in logcat. 

- Ram

**Comment by pumpkinotto** [comment]
first of all, thanks.
ok this is the log
**--------- beginning of /dev/log/system
--------- beginning of /dev/log/main**
*loading the mainmanu*
**D/GoogleMobileAdsUnityPlugin(13076): Calling loadAd() on Android
D/GoogleMobileAdsUnityPlugin(13076): Calling show() on Android**
*loading the  playscene (where i don't want ads)*
**D/GoogleMobileAdsUnityPlugin(13076): Calling loadAd() on Android
D/GoogleMobileAdsUnityPlugin(13076): Calling hide() on Android**
*back to main menu*
**D/GoogleMobileAdsUnityPlugin(13076): Calling loadAd() on Android
D/GoogleMobileAdsUnityPlugin(13076): Calling show() on Android**

so, the ads doesn't disappear.
i think is because the app create 2 ads (the second over the first) and hide the second but not the first.
probably because i have the "AdScript" attachet to the maincamera of each level.
the problem is that when the game load the mainmenu it create an ad then it change to another scene and the MainMenuCamera (and the script) isn't loaded but the ads is still there.
i think i should use only 1 script in the main but when i try to call adscript.bannerview.hide() from another scrip it give me the null reference.
any ideas?
thanks
ps 
sorry for the bad english

**Comment by rampara** [comment]
If you make variables static they should be accessible from other scripts. You can also hide the ad in OnDisabled() which is called during a scene change .

- Ram

**Comment by pumpkinotto** [comment]
yes i have made variables public but if i write this

*AdScript*
**public bool example;**
*HideScript*
**public AdScript adscript;
void start () {
adscript.bannerview.hide();
}**

the console give me the error null reference.
and the inspector ask where it can find the AdScript
usually i have to put the object where adscript is attached, but in this case the gameobject is in another scene and i don't know how to link it.

about the OnDisabled() i don't know what is it? i think is a void but where i have to put it.

thanks

**Comment by rampara** [comment]
You would need to follow the instructions in the link I gave in my previous comment to access variables from another script. OnDisable() does have a return type of void and it is called on game objects during a change of scene. You can try hiding the ad in the OnDisable() method for your main camera in the first scene. 

- Ram

**Comment by pumpkinotto** [comment]
ok thaks,
last question, is normal that i cannot use bannerview.something outside the void where i create it?
thanks

**Comment by rampara** [comment]
Is it possible to hide the ad before you transition to the new scene? If you can post a code snippet of where you are creating the banner and where you are trying to access it I can try and be of more help.

- Ram

**Comment by pumpkinotto** [comment]
using UnityEngine;
using System.Collections;
using GoogleMobileAds.Api;

public class AdMob : MonoBehaviour {

	public BannerView bannerView;


	void Start () {
		AdShow ();

	}
	public void AdShow () 
	{
		// Create a 320x50 banner at the top of the screen.
		BannerView bannerView = new BannerView(
			"ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXX", AdSize.SmartBanner, AdPosition.Top);
		// Create an empty ad request.
		AdRequest request = new AdRequest.Builder().Build();
		// Load the banner with the request.
		bannerView.LoadAd(request);
                //this doesn't work
		if(Application.loadedLevelName == "Base")
			bannerView.Hide();
		else 
			bannerView.Show ();


	}
	void update ()
	{


	}

}

**Comment by rampara** [comment]
After you create the bannerView where are you trying to access it?

- Ram

**Comment by pumpkinotto** [comment]
using UnityEngine;
using System.Collections;
using GoogleMobileAds.Api;

public class **ScriptThatIsInTheMainSceneWhereIDontWantTheBanner** : MonoBehaviour {
//in the inspector it want the gameobject where the script could be find
public AdMob(script) admob;


void Start () {
//this give me *null reference exeption*
 admob.bannerview.hide();

}

void OnDisable ()
{
admob.bannervier.Show();

}

}

**Comment by rampara** [comment]
In the AdMob class try including 

void OnDisable(){
  bannerView.Hide();
}

bannerView.Destroy() might be a better idea to avoid memory leaks if you are no longer using the bannerView.

- Ram

**Comment by pumpkinotto** [comment]
if write
void OnDisable(){
bannerView.Hide(); *or* bannerview.destroy();
}
unity give me **NullReferenceException**

**Comment by rampara** [comment]
Is the OnDisable() method defined in the AdMob class and not ScriptThatIsInTheMainSceneWhereIDontWantTheBanner?

- Ram

**Comment by pumpkinotto** [comment]
on disable is in the AdMob script.
and i don't know why but i get nullreference

**Comment by rampara** [comment]
You are redeclaring bannerView as a local variable in your AdShow() method. It should be 

bannerView = new BannerView(
        "ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXX", AdSize.SmartBanner, AdPosition.Top);

- Ram

**Comment by pumpkinotto** [comment]
ok it worked,
thank you very very much.
thanks again.
Tommaso
