### ISSUE TITLE
Error: use of undeclared identifier ID GAD SIMULATOR

### ISSUE THREAD

**Issue by KyDenZ** [googleads/googleads-mobile-plugins#78]
Hello,

I think you have a problem with the emulation ID.
I want to know how to pouur settle this problem, and if once this problem is resolved, the advertising will be functional on all iphones
![sans titre-1](https://cloud.githubusercontent.com/assets/7247673/6446766/6f794aea-c10d-11e4-828a-1991b4abed73.jpg)
![sans titre-2](https://cloud.githubusercontent.com/assets/7247673/6446767/6f7c1c66-c10d-11e4-9166-1593f0d0fd6c.jpg)

thank you

**Comment by RedBrogdon** [comment]
The GAD_SIMULATOR_ID constant has been removed from the latest version of the iOS SDK (7.0) because it is no longer needed. We have changed the SDK to always serve test ads to apps running on a simulator.  You still need to call addTestDevices when running on a hardware device, but there is no longer any need to do this to force test ads on the simulator.

Basically, you can comment out the line that's giving you the error, and your app will compile and still receive test ads on the simulator.

**Comment by KyDenZ** [comment]
Okay, thank you

But once the application has sent Apple, appear coming adverts?

**Comment by rampara** [comment]
Can you list the issues you see in the issue navigator?

- Ram

**Comment by KyDenZ** [comment]
I do not cromprends what you want.

I'm sorry, I discovered Xcode for porting my game on IOS

Or I have to go to find the information?

**Comment by rampara** [comment]
![screen shot 2015-03-03 at 2 55 15 pm](https://cloud.githubusercontent.com/assets/11047881/6474454/aa5517cc-c1b5-11e4-9af1-c26f6b2be0c0.png)

This view of the log navigator shows all errors and issues.

- Ram

**Comment by KyDenZ** [comment]
Thank you for the information, so here the record
![clone of os x mavericks-2015-03-04-00-03-38](https://cloud.githubusercontent.com/assets/7247673/6474585/4a7a0536-c202-11e4-8090-694b74957794.png)
![clone of os x mavericks-2015-03-04-00-04-03](https://cloud.githubusercontent.com/assets/7247673/6474586/4a7c780c-c202-11e4-86fe-922d6d9f9263.png)

**Comment by rampara** [comment]
You don't seem to have any errors. You can switch to the all issues view at the top to see only errors and warnings. Keep in mind you will not be able to run a Unity project on an iOS simulator. It will have to be run on actual iOS hardware.

- Ram

**Comment by KyDenZ** [comment]
![clone of os x mavericks-2015-03-04-00-15-30](https://cloud.githubusercontent.com/assets/7247673/6474727/aa7debf4-c203-11e4-86e9-8a72e5c7104a.png)

**Comment by rampara** [comment]
There does not seem to be any errors. You should be able to run the application. Keep in mind you Unity applications don't work well on the simulator and should be run on actual iOS hardware. 

- Ram

**Comment by KyDenZ** [comment]
Okay, I'll try with an iphone.
And if it works on the iphone, it will work on all iPhones that will download the application on the store?

**Comment by rampara** [comment]
There are can always be issues that arise from differences in hardware or iOS releases but testing on actual devices will be a better bet than using simulators for Unity projects.

http://docs.unity3d.com/Manual/iphone-basic.html

- Ram

**Comment by KyDenZ** [comment]
I downloaded Unity 5, I got an error (ARC), looking on google, I found a solution: add -fno-objc bow to the "compile flags"

Now the application launches, but remains on a black background
Do you have the same problem?

**Comment by rampara** [comment]
v.2.2.1 of the Unity plugin supports Unity 5.0 and ARC for iOS.

- Ram

**Comment by KyDenZ** [comment]
I have a error compilation with mscorlib.dll

**Comment by KyDenZ** [comment]
Thank you
