### ISSUE TITLE
Parse Issue Module 'GoogleMobileAds' not found

### ISSUE THREAD

**Issue by Surpent** [googleads/googleads-mobile-plugins#79]
Hi.
I have a problem with the new version of the SDK.
Do you help me?

Unity 4.6.2f1
with Google Play Games Plugin for Unity v0.9.11

Xcode 6.1.1  iOS SDK 8.1
Google Mobile Ads SDK iOS 7.0.0
gpg-cpp-sdk 1.3
google-plus-ios-sdk 1.7.1
GooglePlayGames-iOS-SDK.v3.1.1

Thank you.

**Comment by RedBrogdon** [comment]
Github issues are meant for people who have found and verified issues in the SDK examples or plugins. The best place to ask for help in using the SDK is StackOverflow:

http://stackoverflow.com/questions/tagged/admob

or the Mobile Ads SDK Forum:

https://groups.google.com/forum/#!forum/google-admob-ads-sdk

Thanks!

**Comment by Surpent** [comment]
@RedBrogdon 
I'm understand.
Thank you.
