### ISSUE TITLE
Admob flickering

### ISSUE THREAD

**Issue by galkon** [googleads/googleads-mobile-plugins#81]
I have implemented admob using unity for iPhone. I hide ads during game play then show them during the menus.

Every now and then just after I hide the ad I get a flicker of the ad that was just hidden. This does not happen all the time but it is certainly reproducible anybody else had this?

**Comment by rampara** [comment]
I am unable to replicate this issue but from the plugin code you can see that hide functionality for a  banner is implemented simply by setting the hidden property of a UIView to true. If there is flickering it is likely a rendering issue and not something from the plugin. 

- Ram
