### ISSUE TITLE
Need a new branch for admob sdk 7.0.0 and unity 5.

### ISSUE THREAD

**Issue by ghost** [googleads/googleads-mobile-plugins#82]
It's a lot of errors. Who can commit a compatible version without change code is better.Thank you!

**Comment by rampara** [comment]
The current version of the plugin is now v2.2 and includes support for both Unity 5 and Google Mobile Ads SDK v7.0.0. If you are running Unity 5.0 you will have to delete the top-level Android manifest from the Assets/Plugins/Android folder.

Ram
