### ISSUE TITLE
Can we expect a new release soon?

### ISSUE THREAD

**Issue by jjjuande** [googleads/googleads-mobile-plugins#86]
The newest one has almost a year and is 13 commits behind.

Thanks!

**Comment by spartan029** [comment]
I'm also wondering about this. Hoping for a new release soon.
Thanks!

**Comment by DGLWilkins** [comment]
Same here

**Comment by Mikejinhua** [comment]
Oh,MGD! Thanks , I had bought prime31 plugin.This version is too old to support unity 5 and google sdk 7.

**Comment by rampara** [comment]
The current version of the plugin is now v2.2 and includes support for both Unity 5 and Google Mobile Ads SDK v7.0.0. If you are running Unity 5.0 you will have to delete the top-level Android manifest from the Assets/Plugins/Android folder.

- Ram
