### ISSUE TITLE
After Adding package 2.2 to project Input.TouchCount always returns zero

### ISSUE THREAD

**Issue by nurdwerks** [googleads/googleads-mobile-plugins#88]
Before importing package, on android the application displays the correct TouchCount value.

After importing the package, the android application always displays zero.
When debugging the script executing on android, the value inspected is always zero.

The issue also occurs in IOS builds.

The script below is attached to an Text UI component in Unity 5.0.0f4

```csharp
using UnityEngine;
using UnityEngine.UI;

public class TouchCounter : MonoBehaviour {
	void Update () {
		this.GetComponent<Text>().text = "" + Input.touchCount;
	}
}
```

**Comment by jjjuande** [comment]
I've tried that code and it works for me with the last release (2.2) installed and one banner at the top of the screen. Maybe you are missing something...

**Comment by robertwahler** [comment]
I'm having problems too.  It seems that Input.GetMouseButtonDown() no longer works with 2.2.

I wonder if this issue is due to the changed AndroidManifest.xml?  Here is a related issue:
http://answers.unity3d.com/questions/915011/touch-no-longer-works-on-android-in-unity-5.html

**Comment by robertwahler** [comment]
I was able to restore Input functionality by deleting the entire file at Assets/Plugins/Android/AndroidManifest.xml and adding the following line to my Google Play Games manifest snippet at Assets/Plugins/Android/MainLibProj/AndroidManifest.xml:
    
    <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />

**Comment by nurdwerks** [comment]
Interesting, I've been able to get it working by removing that line entirely from my manifest.

Also this affects IOS builds

**Comment by rampara** [comment]
If you are running v2.2 of the Google Mobile Ads Unity plugin with Unity 5.0 you can delete the top-level Android manifest in the Assets/Plugins/Android directory. This should fix the touch count always returning  as 0.

- Ram

**Comment by nurdwerks** [comment]
@rampara this also works. 

IOS still has the same issue though.

**Comment by rampara** [comment]
I am unable to replicate the issue on iOS @nurdwerks . Would you be able to attach an iOS project where you are not receiving touch input?

- Ram
