### ISSUE TITLE
Low Performance with admob when the device is offline

### ISSUE THREAD

**Issue by Bobszee** [googleads/googleads-mobile-plugins#90]
Hi!

I have a question. I use your google admob unity plugin.
When i am online its working fine, i request an Interstitial AD and show it, the performance is good, after the AD closed. But if i am offline, i cant Destroy the AD and the process and i have frame drops in the game every time. How can i shut down the process, when i am offline?
It would be nice, when the app is offline, then the Admob process will be shut down. How can i do that?

 if (Application.internetReachability != NetworkReachability.NotReachable)
{
//player online
//working ad process
}
else
{
//offline
//shut down ad process
}

THX!

**Comment by rampara** [comment]
Why can you not call destroy on an interstitial when there is no network connectivity? 

- Ram

**Comment by Bobszee** [comment]
The interstitial destroy is working, but the performance is bad. When i have a fullscreen ad and i click to close in top right of the screen, the performance is nice. The interstitial.destroy not used to performance, just the close in the ads. My english not the best, but i can make a video for the error.

**Comment by rampara** [comment]
A video of the error would be great.

- Ram

**Comment by rampara** [comment]
Closed to to lack of activity. If this problem still exists, feel free to re-open to issue.

Ram
