### ISSUE TITLE
Ads not showing on IOS

### ISSUE THREAD

**Issue by danix1h** [googleads/googleads-mobile-plugins#92]
Hello everybody,

I'm using the latest version of this plugin, everything works perfect on Android, my script and GoogleMobileAdsDemoScript.cs script works perfect on Android, but they don't work on IOS, banner ads and interstitial ads not showing. Ad unit id is correct, everything should work fine, but no ads showing.

**Comment by danix1h** [comment]
Hello,
I,m also getting this error: 
HandleFailedToReceiveAd event received with message: Failed to receive ad with error: Request Error: No ad to show.
As I said in my first post, everything works perfectly on Android, but on IOS even the demo script which comes with the plugin, ads not working.

**Comment by rampara** [comment]
In your Admob account have you registered your adUnit id for an iOS application?

- Ram

**Comment by danix1h** [comment]
Hello,

Yes, I have adUnit for Android and for IOS. I have checked several times whether or not, the adUnit is correct.

**Comment by rampara** [comment]
Are you able to display test ads?

- Ram

**Comment by danix1h** [comment]
Hello,
Sorry for my late replay! Yes ads are showing using test device/test ads.

**Comment by rampara** [comment]
Can you provide your ad unit id?

- Ram

**Comment by danix1h** [comment]
Banner ads:ca-app-pub-3172839635054563/1282379139
Interstitial ads:ca-app-pub-3172839635054563/2759112338

**Comment by rampara** [comment]
Using the ad units you provided I was able to receive fill for live ads. If you want to follow up with AdMob in regards to ad performance, you can do so at https://support.google.com/admob/v2/contact/ads_performance.

- Ram

**Comment by danix1h** [comment]
I'll try something and if its not working I'll let you know. Thanks for your time !

**Comment by stowy** [comment]
@DGP13 please post your concern on our [developer forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines)), someone will be happy to assist you.
