### ISSUE TITLE
Cross compilation job AdmobUnity.dll failed.

### ISSUE THREAD

**Issue by rbreve** [googleads/googleads-mobile-plugins#93]
When trying to Build for iOS I get this error:

 Error building Player: UnityException: Cross compilation failed.

UnityEngine.UnityException: Failed AOT cross compiler: /Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/mono-xcompiler-wrapper.sh --aot=full,asmonly,nodebug,static,outfile="AdmobUnity.dll.s" "AdmobUnity.dll"  current dir : /Users/robertobreve/Developer/Unity/Crecer/Temp/StagingArea/Data/Managed
 result file exists: False. Timed out: False

**Comment by rampara** [comment]
Which version of Unity are you using?

- Ram

**Comment by rbreve** [comment]
Version 5

**Comment by rampara** [comment]
I am having trouble replicating this issue. Would you be able to attach a Unity project where you are getting this error?

- Ram

**Comment by rbreve** [comment]
I'm getting the same error using the sample scene AdmobTest

![screenshot 2015-04-13 17 56 57](https://cloud.githubusercontent.com/assets/23524/7127802/891c02c0-e206-11e4-9174-eb09d070e7a7.png)

**Comment by rampara** [comment]
Are you using the Google Mobile Ads Unity plugin linked at https://github.com/googleads/googleads-mobile-plugins/releases? Our plugin does not create or use AdmobUnity.dll.

- Ram

**Comment by rampara** [comment]
Closed to to lack of activity. If this problem still exists, feel free to re-open to issue.

- Ram
