### ISSUE TITLE
AdRequest TestDeviceSimulator Showing real ads

### ISSUE THREAD

**Issue by Brainversation** [googleads/googleads-mobile-plugins#94]
I hope I am using this and/or understand this correctly.

```cs
private static AdRequest createAdRequest(){
		return new AdRequest.Builder()
		.AddTestDevice(AdRequest.TestDeviceSimulator)
		.SetGender(Gender.Unknown)
		.TagForChildDirectedTreatment(false)
		.Build();
	}
```

That is the code I am using and it still showing real ads, instead of test ones. From my understanding if you use the line:

```cs
.AddTestDevice(AdRequest.TestDeviceSimulator)
```

its supposed to only show test ads on all devices.

If that is not correct can you give an example on how I can do this.

Thank you for your help and time.

**Comment by rampara** [comment]
After running your application and receiving the first live ad, logcat should contain the following line

I/Ads﹕ Use AdRequest.Builder.addTestDevice("XXXXXXXXXXXXXXXX") to get test ads on this device.

"XXXXXXXXXXXXXXXX" will be a device specific hash. Call .AddTestDevice("XXXXXXXXXXXXXXXX") on your ad request to receive test ads on that device. 

- Ram

**Comment by Brainversation** [comment]
Thanks worked like a charm! I had to make a development build to see it, but once I knew what I was looking for it helped more. You might want to add this to the read me.

Also I don't know if you would know the answer, or where to find it, but am I allowed to have ads during alpha/beta testing on the app stores?

Thanks again!

**Comment by rampara** [comment]
If your alpha/ beta testing is being performed by actual users, displaying live ad is fine. On the other hand, if this testing is performed by individuals in QA or developmental role, test ads should be used.

- Ram

**Comment by Brainversation** [comment]
That makes sense, thanks for the help!
