### ISSUE TITLE
Ads not showing, log returns 'No Fill'

### ISSUE THREAD

**Issue by Wolfos** [googleads/googleads-mobile-plugins#95]
I'm trying to show a banner ad in my Unity Android app (tried both AdSize.Banner and AdSize.SmartBanner), but nothing happens when I test. I tried adding my test device (request.TestDevices.Add), but the same thing. The log shows only "No Fill".

**Comment by rampara** [comment]
Are you not able to successfully receive test ads? Can you post a code snippet of your ad request?

- Ram

**Comment by rampara** [comment]
Closed to to lack of activity. If this problem still exists, feel free to re-open to issue.

- Ram
