### ISSUE TITLE
Android will not build already added Lcom/google/unity/ads/Banner$1$1

### ISSUE THREAD

**Issue by zacthespack** [googleads/googleads-mobile-plugins#96]
After upgrading to Unity 5 and the new google ads plugin, when i try to build the android version of my game i get the below error:

>Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
>/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/Zachary/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/Unity.app/Contents/BuildTargetTools/AndroidPlayer/sdktools.jar" -

>stderr[

>UNEXPECTED TOP-LEVEL EXCEPTION:
>java.lang.IllegalArgumentException: already added: Lcom/google/unity/ads/Banner$1$1;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at SDKMain.main(SDKMain.java:129)
1 error; aborting
]
stdout[
processing archive bin/classes.jar...
processing com/unity3d/player/a$1.class...
processing com/unity3d/player/a$2.class...
processing com/unity3d/player/a$a.class...
processing com/unity3d/player/a.class...
processing com/unity3d/player/b$1.class...
processing com/unity3d/player/b$2.class...
processing com/unity3d/player/b.class...
processing com/unity3d/player/c.class...
processing com/unity3d/player/d$1.class...
processing com/unity3d/player/d$2.class...
processing com/unity3d/player/d.class...
processing com/unity3d/player/e.class...
processing com/unity3d/player/f.class...
processing com/unity3d/player/g.class...
processing com/unity3d/player/h.class...
processing com/unity3d/player/i.class...
processing com/unity3d/player/j$1.class...
processing com/unity3d/player/j$2$1$1.class...
processing com/unity3d/player/j$2$1.class...
processing com/unity3d/player/j$2.class...
processing com/unity3d/player/j.class...
processing com/unity3d/player/k$1.class...
processing com/unity3d/player/k.class...
processing com/unity3d/player/l.class...
processing com/unity3d/player/m.class...
processing com/unity3d/player/n$1.class...
processing com/unity3d/player/n.class...
processing com/unity3d/player/NativeLoader.class...
processing com/unity3d/player/o.class...
processing com/unity3d/player/ReflectionHelper$1.class...
processing com/unity3d/player/ReflectionHelper$a.class...
processing com/unity3d/player/ReflectionHelper.class...
processing com/unity3d/player/p.class...
processing com/unity3d/player/q$1.class...
processing com/unity3d/player/q$2.class...
processing com/unity3d/player/q$3.class...
processing com/unity3d/player/q.class...
processing com/unity3d/player/r.class...
processing com/unity3d/player/s.class...
processing com/unity3d/player/UnityPlayer$1.class...
processing com/unity3d/player/UnityPlayer$2.class...
processing com/unity3d/player/UnityPlayer$3.class...
processing com/unity3d/player/UnityPlayer$4.class...
processing com/unity3d/player/UnityPlayer$5.class...
processing com/unity3d/player/UnityPlayer$6.class...
processing com/unity3d/player/UnityPlayer$7.class...
processing com/unity3d/player/UnityPlayer$8.class...
processing com/unity3d/player/UnityPlayer$9.class...
processing com/unity3d/player/UnityPlayer$10.class...
processing com/unity3d/player/UnityPlayer$11.class...
processing com/unity3d/player/UnityPlayer$12$1.class...
processing com/unity3d/player/UnityPlayer$12.class...
processing com/unity3d/player/UnityPlayer$13.class...
processing com/unity3d/player/UnityPlayer$14.class...
processing com/unity3d/player/UnityPlayer$15.class...
processing com/unity3d/player/UnityPlayer$16.class...
processing com/unity3d/player/UnityPlayer$17.class...
processing com/unity3d/player/UnityPlayer$18.class...
processing com/unity3d/player/UnityPlayer$a.class...
processing com/unity3d/player/UnityPlayer$b.class...
processing com/unity3d/player/UnityPlayer$c.class...
processing com/unity3d/player/UnityPlayer.class...
processing com/unity3d/player/UnityPlayerActivity.class...
processing com/unity3d/player/UnityPlayerNativeActivity.class...
processing com/unity3d/player/UnityPlayerProxyActivity.class...
processing com/unity3d/player/t.class...
processing com/unity3d/player/u$1.class...
processing com/unity3d/player/u.class...
processing com/unity3d/player/WWW.class...
processing org/fmod/FMODAudioDevice$a.class...
processing org/fmod/FMODAudioDevice.class...
processing org/fmod/a.class...
processing bin/classes/./com/eskivogame/R$attr.class...
processing bin/classes/./com/eskivogame/R$color.class...
processing bin/classes/./com/eskivogame/R$drawable.class...
processing bin/classes/./com/eskivogame/R$id.class...
processing bin/classes/./com/eskivogame/R$integer.class...
processing bin/classes/./com/eskivogame/R$raw.class...
processing bin/classes/./com/eskivogame/R$string.class...
processing bin/classes/./com/eskivogame/R$style.class...
processing bin/classes/./com/eskivogame/R$styleable.class...
processing bin/classes/./com/eskivogame/R.class...
processing bin/classes/./com/google/android/gms/R$attr.class...
processing bin/classes/./com/google/android/gms/R$color.class...
processing bin/classes/./com/google/android/gms/R$drawable.class...
processing bin/classes/./com/google/android/gms/R$id.class...
processing bin/classes/./com/google/android/gms/R$integer.class...
processing bin/classes/./com/google/android/gms/R$raw.class...
processing bin/classes/./com/google/android/gms/R$string.class...
processing bin/classes/./com/google/android/gms/R$style.class...
processing bin/classes/./com/google/android/gms/R$styleable.class...
processing bin/classes/./com/google/android/gms/R.class...
processing bin/classes/./com/google/unity/R$attr.class...
processing bin/classes/./com/google/unity/R$color.class...
processing bin/classes/./com/google/unity/R$drawable.class...
processing bin/classes/./com/google/unity/R$id.class...
processing bin/classes/./com/google/unity/R$integer.class...
processing bin/classes/./com/google/unity/R$raw.class...
processing bin/classes/./com/google/unity/R$string.class...
processing bin/classes/./com/google/unity/R$style.class...
processing bin/classes/./com/google/unity/R$styleable.class...
processing bin/classes/./com/google/unity/R.class...
processing archive plugins/./AndroidStore.jar...
ignored resource META-INF/MANIFEST.MF
processing com/soomla/rewards/VirtualItemReward.class...
processing com/soomla/store/IStoreAssets.class...
processing com/soomla/store/SoomlaStore$1.class...
processing com/soomla/store/SoomlaStore$2.class...
processing com/soomla/store/SoomlaStore$3$1.class...
processing com/soomla/store/SoomlaStore$3.class...
processing com/soomla/store/SoomlaStore$4$1.class...
processing com/soomla/store/SoomlaStore$4.class...
processing com/soomla/store/SoomlaStore$5$1.class...
processing com/soomla/store/SoomlaStore$5.class...
processing com/soomla/store/SoomlaStore.class...
processing com/soomla/store/StoreConfig.class...
processing com/soomla/store/StoreForeground.class...
processing com/soomla/store/StoreInventory.class...
processing com/soomla/store/billing/IIabService.class...
processing com/soomla/store/billing/IabCallbacks$IabInitListener.class...
processing com/soomla/store/billing/IabCallbacks$OnConsumeListener.class...
processing com/soomla/store/billing/IabCallbacks$OnFetchSkusDetailsListener.class...
processing com/soomla/store/billing/IabCallbacks$OnPurchaseListener.class...
processing com/soomla/store/billing/IabCallbacks$OnRestorePurchasesListener.class...
processing com/soomla/store/billing/IabCallbacks.class...
processing com/soomla/store/billing/IabException.class...
processing com/soomla/store/billing/IabHelper$1.class...
processing com/soomla/store/billing/IabHelper$2.class...
processing com/soomla/store/billing/IabHelper$3.class...
processing com/soomla/store/billing/IabHelper$4.class...
processing com/soomla/store/billing/IabHelper$5.class...
processing com/soomla/store/billing/IabHelper$6.class...
processing com/soomla/store/billing/IabHelper$7.class...
processing com/soomla/store/billing/IabHelper$8.class...
processing com/soomla/store/billing/IabHelper$FetchSkusDetailsFinishedListener.class...
processing com/soomla/store/billing/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/soomla/store/billing/IabHelper$OnIabSetupFinishedListener.class...
processing com/soomla/store/billing/IabHelper$RestorePurchasessFinishedListener.class...
processing com/soomla/store/billing/IabHelper.class...
processing com/soomla/store/billing/IabInventory.class...
processing com/soomla/store/billing/IabPurchase.class...
processing com/soomla/store/billing/IabResult.class...
processing com/soomla/store/billing/IabSkuDetails.class...
processing com/soomla/store/data/StorageManager.class...
processing com/soomla/store/data/StoreInfo.class...
processing com/soomla/store/data/StoreJSONConsts.class...
processing com/soomla/store/data/VirtualCurrencyStorage.class...
processing com/soomla/store/data/VirtualGoodsStorage.class...
processing com/soomla/store/data/VirtualItemStorage.class...
processing com/soomla/store/domain/MarketItem$Managed.class...
processing com/soomla/store/domain/MarketItem.class...
processing com/soomla/store/domain/PurchasableVirtualItem.class...
processing com/soomla/store/domain/VirtualCategory.class...
processing com/soomla/store/domain/VirtualItem.class...
processing com/soomla/store/domain/virtualCurrencies/VirtualCurrency.class...
processing com/soomla/store/domain/virtualCurrencies/VirtualCurrencyPack.class...
processing com/soomla/store/domain/virtualGoods/EquippableVG$EquippingModel.class...
processing com/soomla/store/domain/virtualGoods/EquippableVG.class...
processing com/soomla/store/domain/virtualGoods/LifetimeVG.class...
processing com/soomla/store/domain/virtualGoods/SingleUsePackVG.class...
processing com/soomla/store/domain/virtualGoods/SingleUseVG.class...
processing com/soomla/store/domain/virtualGoods/UpgradeVG.class...
processing com/soomla/store/domain/virtualGoods/VirtualGood.class...
processing com/soomla/store/events/BillingNotSupportedEvent.class...
processing com/soomla/store/events/BillingSupportedEvent.class...
processing com/soomla/store/events/CurrencyBalanceChangedEvent.class...
processing com/soomla/store/events/GoodBalanceChangedEvent.class...
processing com/soomla/store/events/GoodEquippedEvent.class...
processing com/soomla/store/events/GoodUnEquippedEvent.class...
processing com/soomla/store/events/GoodUpgradeEvent.class...
processing com/soomla/store/events/IabServiceStartedEvent.class...
processing com/soomla/store/events/IabServiceStoppedEvent.class...
processing com/soomla/store/events/ItemPurchaseStartedEvent.class...
processing com/soomla/store/events/ItemPurchasedEvent.class...
processing com/soomla/store/events/MarketItemsRefreshFailedEvent.class...
processing com/soomla/store/events/MarketItemsRefreshFinishedEvent.class...
processing com/soomla/store/events/MarketItemsRefreshStartedEvent.class...
processing com/soomla/store/events/MarketPurchaseCancelledEvent.class...
processing com/soomla/store/events/MarketPurchaseEvent.class...
processing com/soomla/store/events/MarketPurchaseStartedEvent.class...
processing com/soomla/store/events/MarketRefundEvent.class...
processing com/soomla/store/events/RestoreTransactionsFinishedEvent.class...
processing com/soomla/store/events/RestoreTransactionsStartedEvent.class...
processing com/soomla/store/events/SoomlaStoreInitializedEvent.class...
processing com/soomla/store/events/UnexpectedStoreErrorEvent.class...
processing com/soomla/store/exceptions/InsufficientFundsException.class...
processing com/soomla/store/exceptions/NotEnoughGoodsException.class...
processing com/soomla/store/exceptions/VirtualItemNotFoundException.class...
processing com/soomla/store/purchaseTypes/PurchaseType.class...
processing com/soomla/store/purchaseTypes/PurchaseWithMarket.class...
processing com/soomla/store/purchaseTypes/PurchaseWithVirtualItem.class...
processing archive plugins/./AndroidStoreGooglePlay.jar...
ignored resource META-INF/MANIFEST.MF
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService.class...
processing com/soomla/store/billing/google/Consts$PurchaseState.class...
processing com/soomla/store/billing/google/Consts$ResponseCode.class...
processing com/soomla/store/billing/google/Consts.class...
processing com/soomla/store/billing/google/GoogleIabHelper$1.class...
processing com/soomla/store/billing/google/GoogleIabHelper$2.class...
processing com/soomla/store/billing/google/GoogleIabHelper$3.class...
processing com/soomla/store/billing/google/GoogleIabHelper$4$1.class...
processing com/soomla/store/billing/google/GoogleIabHelper$4$2.class...
processing com/soomla/store/billing/google/GoogleIabHelper$4.class...
processing com/soomla/store/billing/google/GoogleIabHelper$OnConsumeFinishedListener.class...
processing com/soomla/store/billing/google/GoogleIabHelper$OnConsumeMultiFinishedListener.class...
processing com/soomla/store/billing/google/GoogleIabHelper.class...
processing com/soomla/store/billing/google/GooglePlayIabService$1.class...
processing com/soomla/store/billing/google/GooglePlayIabService$FetchSkusDetailsFinishedListener.class...
processing com/soomla/store/billing/google/GooglePlayIabService$IabActivity.class...
processing com/soomla/store/billing/google/GooglePlayIabService$OnIabPurchaseFinishedListener.class...
processing com/soomla/store/billing/google/GooglePlayIabService$OnIabSetupFinishedListener.class...
processing com/soomla/store/billing/google/GooglePlayIabService$RestorePurchasesFinishedListener.class...
processing com/soomla/store/billing/google/GooglePlayIabService.class...
processing com/soomla/store/billing/google/Security.class...
processing archive plugins/./SoomlaAndroidCore.jar...
ignored resource META-INF/MANIFEST.MF
processing com/soomla/AndroidBus$1.class...
processing com/soomla/AndroidBus$2.class...
processing com/soomla/AndroidBus$3.class...
processing com/soomla/AndroidBus.class...
processing com/soomla/BusProvider.class...
processing com/soomla/Foreground$1.class...
processing com/soomla/Foreground$ForegroundNew$1.class...
processing com/soomla/Foreground$ForegroundNew.class...
processing com/soomla/Foreground$ForegroundOld.class...
processing com/soomla/Foreground.class...
processing com/soomla/Schedule$1.class...
processing com/soomla/Schedule$DateTimeRange.class...
processing com/soomla/Schedule$Recurrence.class...
processing com/soomla/Schedule.class...
processing com/soomla/Soomla.class...
processing com/soomla/SoomlaApp$1.class...
processing com/soomla/SoomlaApp.class...
processing com/soomla/SoomlaConfig.class...
processing com/soomla/SoomlaEntity.class...
processing com/soomla/SoomlaMarketUtils.class...
processing com/soomla/SoomlaUtils.class...
processing com/soomla/data/JSONConsts.class...
processing com/soomla/data/KeyValDatabase$DatabaseHelper.class...
processing com/soomla/data/KeyValDatabase.class...
processing com/soomla/data/KeyValueStorage.class...
processing com/soomla/data/RewardStorage.class...
processing com/soomla/e<message truncated>

It builds fine for iOS. Thanks for any help

**Comment by rampara** [comment]
The error you are seeing is caused when you have same jar library included twice. Check to make sure the plugin jar is not included more than once.

- Ram

**Comment by rampara** [comment]
Closed to to lack of activity. If this problem still exists, feel free to re-open to issue.

Ram
