### ISSUE TITLE
Some devices gives crashes after showing interstatial ads

### ISSUE THREAD

**Issue by Lordinarius** [googleads/googleads-mobile-plugins#97]
Hi
Some devices are giving crash after showing interstatial or after closing the ad. 

Usually android version 4.2

I have 20 crash reports same as this and they are all 4.2

java.lang.Error: FATAL EXCEPTION [UnityMain]
Unity version : 5.0.0f4
Device model : Digma Optima 10.2 3G TT1040MG
Device fingerprint: alps/mr900/mr900:4.2.2/JDQ39/1403577075:user/release-keys

Caused by: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000020
Build fingerprint: 'alps/mr900/mr900:4.2.2/JDQ39/1403577075:user/release-keys'
Revision: '0'
pid: 24534, tid: 24550, name: UnityMain >>> com.xxx.xxx<<<
r0 00000000 r1 00000000 r2 ffffffff r3 600159f8
r4 00000000 r5 6015e7a0 r6 00000000 r7 00000000
r8 00000001 r9 63be9001 sl 00000002 fp 00000001
ip 00000002 sp 5f1499d8 lr 405df705 pc 405e1636 cpsr 3a353730

at libEGL.00001636(Native Method)
at Unknown.00003009(Unknown Source)

**Comment by rampara** [comment]
What devices are you seeing this crash on and what version of the Unity plugin are they using? Are you able to replicate this crash? If so would you be able to provide logs?

- Ram

**Comment by Lordinarius** [comment]
Unfortunately, i don't have one of these devices. Here the list of devices.
![devices](https://cloud.githubusercontent.com/assets/3225847/7510414/63f7fafc-f4a4-11e4-80aa-1c345db95f40.JPG)

**Comment by rampara** [comment]
Using an Alcatel One Touch on Android 4.2.2 I was unable to replicate this issue. Without access to any of the other listed devices or more information, I won't be able to troubleshoot any further.

- Ram
