### ISSUE TITLE
Click banner is not working on Android

### ISSUE THREAD

**Issue by Haegon** [googleads/googleads-mobile-plugins#99]
Only Android, can not click ad. (iOS work well. banner links webpage)

However, banner is shown on screen. 

I test on Galaxy note 4 and Galaxy S3.

**Comment by Haegon** [comment]
at v2.2

**Comment by rampara** [comment]
If you are using using a version of Unity earlier than 5.0, you will have to update your Android manifest file as stated at https://github.com/googleads/googleads-mobile-plugins/blob/master/unity/README.md.

**Comment by rampara** [comment]
Closed to to lack of activity. If this problem still exists, feel free to re-open to issue.

- Ram
